package com.sh3h.dataprovider.greendaoDao;

import android.database.sqlite.SQLiteDatabase;

import com.sh3h.dataprovider.greendaoEntity.BIAOKAXX;
import com.sh3h.dataprovider.greendaoEntity.BiaoWuGD;
import com.sh3h.dataprovider.greendaoEntity.ChaoBiaoBZ;
import com.sh3h.dataprovider.greendaoEntity.ChaoBiaoGJ;
import com.sh3h.dataprovider.greendaoEntity.ChaoBiaoJL;
import com.sh3h.dataprovider.greendaoEntity.ChaoBiaoRW;
import com.sh3h.dataprovider.greendaoEntity.ChaoBiaoSJ;
import com.sh3h.dataprovider.greendaoEntity.ChaoBiaoZT;
import com.sh3h.dataprovider.greendaoEntity.ChaoBiaoZTFL;
import com.sh3h.dataprovider.greendaoEntity.CiYuXX;
import com.sh3h.dataprovider.greendaoEntity.DengLuLS;
import com.sh3h.dataprovider.greendaoEntity.DingEJJBL;
import com.sh3h.dataprovider.greendaoEntity.DuoMeiTXX;
import com.sh3h.dataprovider.greendaoEntity.FeiYongZC;
import com.sh3h.dataprovider.greendaoEntity.FeiYongZKL;
import com.sh3h.dataprovider.greendaoEntity.GongGaoXX;
import com.sh3h.dataprovider.greendaoEntity.GuiJi;
import com.sh3h.dataprovider.greendaoEntity.HuanBiaoJL;
import com.sh3h.dataprovider.greendaoEntity.JiChaRW;
import com.sh3h.dataprovider.greendaoEntity.JiChaSJ;
import com.sh3h.dataprovider.greendaoEntity.JianHao;
import com.sh3h.dataprovider.greendaoEntity.JianHaoMX;
import com.sh3h.dataprovider.greendaoEntity.JiaoFeiXX;
import com.sh3h.dataprovider.greendaoEntity.JinEXX;
import com.sh3h.dataprovider.greendaoEntity.MetaInfo;
import com.sh3h.dataprovider.greendaoEntity.NeiFuBZ;
import com.sh3h.dataprovider.greendaoEntity.QianFeiXX;
import com.sh3h.dataprovider.greendaoEntity.ReXianGD;
import com.sh3h.dataprovider.greendaoEntity.RenwuXX;
import com.sh3h.dataprovider.greendaoEntity.RushPayRW;
import com.sh3h.dataprovider.greendaoEntity.ShuiLiangFTXX;
import com.sh3h.dataprovider.greendaoEntity.UserInfo;
import com.sh3h.dataprovider.greendaoEntity.Users;
import com.sh3h.dataprovider.greendaoEntity.WaiFuCBSJ;
import com.sh3h.dataprovider.greendaoEntity.WaiFuGDDetail;
import com.sh3h.dataprovider.greendaoEntity.WaiFuGDMain;
import com.sh3h.dataprovider.greendaoEntity.WaiFuYY;
import com.sh3h.dataprovider.greendaoEntity.WordsInfo;
import com.sh3h.dataprovider.greendaoEntity.XinXiBG;
import com.sh3h.dataprovider.greendaoEntity.YanChiBiao;
import com.sh3h.dataprovider.greendaoEntity.YuanGongXX;
import com.sh3h.dataprovider.greendaoEntity.ZhuangTaiLXCS;
import com.sh3h.serverprovider.entity.BiaoKaBean;
import com.sh3h.serverprovider.entity.BiaoKaListBean;
import com.sh3h.serverprovider.entity.BiaoKaWholeEntity;
import com.sh3h.serverprovider.entity.XunJianTaskBean;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chaoBiaoBZDaoConfig;
    private final DaoConfig chaoBiaoGJDaoConfig;
    private final DaoConfig chaoBiaoJLDaoConfig;
    private final DaoConfig huanBiaoJLDaoConfig;
    private final DaoConfig ciYuXXDaoConfig;
    private final DaoConfig xinXiBGDaoConfig;
    private final DaoConfig feiYongZKLDaoConfig;
    private final DaoConfig wordsInfoDaoConfig;
    private final DaoConfig dingEJJBLDaoConfig;
    private final DaoConfig feiYongZCDaoConfig;
    private final DaoConfig shuiLiangFTXXDaoConfig;
    private final DaoConfig jianHaoMXDaoConfig;
    private final DaoConfig reXianGDDaoConfig;
    private final DaoConfig jianHaoDaoConfig;
    private final DaoConfig chaoBiaoRWDaoConfig;
    private final DaoConfig chaoBiaoSJDaoConfig;
    private final DaoConfig chaoBiaoZTDaoConfig;
    private final DaoConfig chaoBiaoZTFLDaoConfig;
    private final DaoConfig duoMeiTXXDaoConfig;
    private final DaoConfig guiJiDaoConfig;
    private final DaoConfig neiFuBZDaoConfig;
    private final DaoConfig zhuangTaiLXCSDaoConfig;
    private final DaoConfig bIAOKAXXDaoConfig;
    private final DaoConfig dengLuLSDaoConfig;
    private final DaoConfig metaInfoDaoConfig;
    private final DaoConfig biaoWuGDDaoConfig;
    private final DaoConfig renwuXXDaoConfig;
    private final DaoConfig usersDaoConfig;
    private final DaoConfig waiFuGDDetailDaoConfig;
    private final DaoConfig waiFuGDMainDaoConfig;
    private final DaoConfig waiFuYYDaoConfig;
    private final DaoConfig yanChiBiaoDaoConfig;
    private final DaoConfig jiaoFeiXXDaoConfig;
    private final DaoConfig gongGaoXXDaoConfig;
    private final DaoConfig yuanGongXXDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig jinEXXDaoConfig;
    private final DaoConfig qianFeiXXDaoConfig;
    private final DaoConfig rushPayRWDaoconfig;
    private final DaoConfig jiChaRWDaoconfig;
    private final DaoConfig jiChaSJDaoconfig;
    private final DaoConfig waiFuCBSJDaoConfig;
    private final DaoConfig biaoKaBeanDaoConfig;
    private final DaoConfig biaoKaListBeanDaoConfig;
    private final DaoConfig biaoKaWholeEntityDaoConfig;
    private final DaoConfig xunJianTaskBeanDaoConfig;


    private final ChaoBiaoBZDao chaoBiaoBZDao;
    private final ChaoBiaoGJDao chaoBiaoGJDao;
    private final ChaoBiaoJLDao chaoBiaoJLDao;
    private final HuanBiaoJLDao huanBiaoJLDao;
    private final CiYuXXDao ciYuXXDao;
    private final XinXiBGDao xinXiBGDao;
    private final FeiYongZKLDao feiYongZKLDao;
    private final WordsInfoDao wordsInfoDao;
    private final DingEJJBLDao dingEJJBLDao;
    private final FeiYongZCDao feiYongZCDao;
    private final ShuiLiangFTXXDao shuiLiangFTXXDao;
    private final JianHaoMXDao jianHaoMXDao;
    private final ReXianGDDao reXianGDDao;
    private final JianHaoDao jianHaoDao;
    private final ChaoBiaoRWDao chaoBiaoRWDao;
    private final ChaoBiaoSJDao chaoBiaoSJDao;
    private final ChaoBiaoZTDao chaoBiaoZTDao;
    private final ChaoBiaoZTFLDao chaoBiaoZTFLDao;
    private final DuoMeiTXXDao duoMeiTXXDao;
    private final GuiJiDao guiJiDao;
    private final NeiFuBZDao neiFuBZDao;
    private final ZhuangTaiLXCSDao zhuangTaiLXCSDao;
    private final BIAOKAXXDao bIAOKAXXDao;
    private final DengLuLSDao dengLuLSDao;
    private final MetaInfoDao metaInfoDao;
    private final BiaoWuGDDao biaoWuGDDao;
    private final RenwuXXDao renwuXXDao;
    private final UsersDao usersDao;
    private final WaiFuGDDetailDao waiFuGDDetailDao;
    private final WaiFuGDMainDao waiFuGDMainDao;
    private final WaiFuYYDao waiFuYYDao;
    private final YanChiBiaoDao yanChiBiaoDao;
    private final JiaoFeiXXDao jiaoFeiXXDao;
    private final GongGaoXXDao gongGaoXXDao;
    private final YuanGongXXDao yuanGongXXDao;
    private final UserInfoDao userInfoDao;
    private final JinEXXDao jinEXXDao;
    private final QianFeiXXDao qianFeiXXDao;
    private final RushPayRWDao rushPayRWDao;
    private final JiChaRWDao jiChaRWDao;
    private final JiChaSJDao jiChaSJDao;
    private final WaiFuCBSJDao waiFuCBSJDao;
    private final BiaoKaBeanDao biaoKaBeanDao;
    private final BiaoKaListBeanDao biaoKaListBeanDao;
    private final BiaoKaWholeEntityDao biaoKaWholeEntityDao;
    private final XunJianTaskBeanDao xunJianTaskBeanDao;



    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chaoBiaoRWDaoConfig = daoConfigMap.get(ChaoBiaoRWDao.class).clone();
        chaoBiaoRWDaoConfig.initIdentityScope(type);

        chaoBiaoSJDaoConfig = daoConfigMap.get(ChaoBiaoSJDao.class).clone();
        chaoBiaoSJDaoConfig.initIdentityScope(type);

        chaoBiaoBZDaoConfig = daoConfigMap.get(ChaoBiaoBZDao.class).clone();
        chaoBiaoBZDaoConfig.initIdentityScope(type);

        chaoBiaoGJDaoConfig = daoConfigMap.get(ChaoBiaoGJDao.class).clone();
        chaoBiaoGJDaoConfig.initIdentityScope(type);

        chaoBiaoJLDaoConfig = daoConfigMap.get(ChaoBiaoJLDao.class).clone();
        chaoBiaoJLDaoConfig.initIdentityScope(type);

        huanBiaoJLDaoConfig = daoConfigMap.get(HuanBiaoJLDao.class).clone();
        huanBiaoJLDaoConfig.initIdentityScope(type);

        ciYuXXDaoConfig = daoConfigMap.get(CiYuXXDao.class).clone();
        ciYuXXDaoConfig.initIdentityScope(type);

        xinXiBGDaoConfig = daoConfigMap.get(XinXiBGDao.class).clone();
        xinXiBGDaoConfig.initIdentityScope(type);

        feiYongZKLDaoConfig = daoConfigMap.get(FeiYongZKLDao.class).clone();
        feiYongZKLDaoConfig.initIdentityScope(type);

        wordsInfoDaoConfig = daoConfigMap.get(WordsInfoDao.class).clone();
        wordsInfoDaoConfig.initIdentityScope(type);

        dingEJJBLDaoConfig = daoConfigMap.get(DingEJJBLDao.class).clone();
        dingEJJBLDaoConfig.initIdentityScope(type);

        feiYongZCDaoConfig = daoConfigMap.get(FeiYongZCDao.class).clone();
        feiYongZCDaoConfig.initIdentityScope(type);

        shuiLiangFTXXDaoConfig = daoConfigMap.get(ShuiLiangFTXXDao.class).clone();
        shuiLiangFTXXDaoConfig.initIdentityScope(type);

        jianHaoMXDaoConfig = daoConfigMap.get(JianHaoMXDao.class).clone();
        jianHaoMXDaoConfig.initIdentityScope(type);

        reXianGDDaoConfig = daoConfigMap.get(ReXianGDDao.class).clone();
        reXianGDDaoConfig.initIdentityScope(type);

        jianHaoDaoConfig = daoConfigMap.get(JianHaoDao.class).clone();
        jianHaoDaoConfig.initIdentityScope(type);


        chaoBiaoZTDaoConfig = daoConfigMap.get(ChaoBiaoZTDao.class).clone();
        chaoBiaoZTDaoConfig.initIdentityScope(type);

        chaoBiaoZTFLDaoConfig = daoConfigMap.get(ChaoBiaoZTFLDao.class).clone();
        chaoBiaoZTFLDaoConfig.initIdentityScope(type);

        duoMeiTXXDaoConfig = daoConfigMap.get(DuoMeiTXXDao.class).clone();
        duoMeiTXXDaoConfig.initIdentityScope(type);

        guiJiDaoConfig = daoConfigMap.get(GuiJiDao.class).clone();
        guiJiDaoConfig.initIdentityScope(type);

        neiFuBZDaoConfig = daoConfigMap.get(NeiFuBZDao.class).clone();
        neiFuBZDaoConfig.initIdentityScope(type);

        zhuangTaiLXCSDaoConfig = daoConfigMap.get(ZhuangTaiLXCSDao.class).clone();
        zhuangTaiLXCSDaoConfig.initIdentityScope(type);

        bIAOKAXXDaoConfig = daoConfigMap.get(BIAOKAXXDao.class).clone();
        bIAOKAXXDaoConfig.initIdentityScope(type);

        dengLuLSDaoConfig = daoConfigMap.get(DengLuLSDao.class).clone();
        dengLuLSDaoConfig.initIdentityScope(type);

        metaInfoDaoConfig = daoConfigMap.get(MetaInfoDao.class).clone();
        metaInfoDaoConfig.initIdentityScope(type);

        biaoWuGDDaoConfig = daoConfigMap.get(BiaoWuGDDao.class).clone();
        biaoWuGDDaoConfig.initIdentityScope(type);

        renwuXXDaoConfig = daoConfigMap.get(RenwuXXDao.class).clone();
        renwuXXDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        waiFuGDDetailDaoConfig = daoConfigMap.get(WaiFuGDDetailDao.class).clone();
        waiFuGDDetailDaoConfig.initIdentityScope(type);

        waiFuGDMainDaoConfig = daoConfigMap.get(WaiFuGDMainDao.class).clone();
        waiFuGDMainDaoConfig.initIdentityScope(type);

        waiFuYYDaoConfig = daoConfigMap.get(WaiFuYYDao.class).clone();
        waiFuYYDaoConfig.initIdentityScope(type);

        yanChiBiaoDaoConfig = daoConfigMap.get(YanChiBiaoDao.class).clone();
        yanChiBiaoDaoConfig.initIdentityScope(type);

        jiaoFeiXXDaoConfig = daoConfigMap.get(JiaoFeiXXDao.class).clone();
        jiaoFeiXXDaoConfig.initIdentityScope(type);

        gongGaoXXDaoConfig = daoConfigMap.get(GongGaoXXDao.class).clone();
        gongGaoXXDaoConfig.initIdentityScope(type);

        yuanGongXXDaoConfig = daoConfigMap.get(YuanGongXXDao.class).clone();
        yuanGongXXDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        jinEXXDaoConfig = daoConfigMap.get(JinEXXDao.class).clone();
        jinEXXDaoConfig.initIdentityScope(type);

        qianFeiXXDaoConfig = daoConfigMap.get(QianFeiXXDao.class).clone();
        qianFeiXXDaoConfig.initIdentityScope(type);

        rushPayRWDaoconfig =  daoConfigMap.get(RushPayRWDao.class).clone();
        rushPayRWDaoconfig.initIdentityScope(type);

        jiChaRWDaoconfig = daoConfigMap.get(JiChaRWDao.class).clone();
        jiChaRWDaoconfig.initIdentityScope(type);

        jiChaSJDaoconfig = daoConfigMap.get(JiChaSJDao.class).clone();
        jiChaSJDaoconfig.initIdentityScope(type);

        waiFuCBSJDaoConfig =  daoConfigMap.get(WaiFuCBSJDao.class).clone();
        waiFuCBSJDaoConfig.initIdentityScope(type);

        biaoKaBeanDaoConfig = daoConfigMap.get(BiaoKaBeanDao.class).clone();
        biaoKaBeanDaoConfig.initIdentityScope(type);

        biaoKaListBeanDaoConfig =  daoConfigMap.get(BiaoKaListBeanDao.class).clone();
        biaoKaListBeanDaoConfig.initIdentityScope(type);

        biaoKaWholeEntityDaoConfig =   daoConfigMap.get(BiaoKaWholeEntityDao.class).clone();
        biaoKaWholeEntityDaoConfig.initIdentityScope(type);

        xunJianTaskBeanDaoConfig =   daoConfigMap.get(XunJianTaskBeanDao.class).clone();
        xunJianTaskBeanDaoConfig.initIdentityScope(type);

        chaoBiaoRWDao = new ChaoBiaoRWDao(chaoBiaoRWDaoConfig, this);
        chaoBiaoSJDao = new ChaoBiaoSJDao(chaoBiaoSJDaoConfig, this);
        chaoBiaoBZDao = new ChaoBiaoBZDao(chaoBiaoBZDaoConfig, this);
        chaoBiaoGJDao = new ChaoBiaoGJDao(chaoBiaoGJDaoConfig, this);
        chaoBiaoJLDao = new ChaoBiaoJLDao(chaoBiaoJLDaoConfig, this);
        huanBiaoJLDao = new HuanBiaoJLDao(huanBiaoJLDaoConfig, this);
        ciYuXXDao = new CiYuXXDao(ciYuXXDaoConfig, this);
        xinXiBGDao = new XinXiBGDao(xinXiBGDaoConfig, this);
        feiYongZKLDao = new FeiYongZKLDao(feiYongZKLDaoConfig, this);
        wordsInfoDao = new WordsInfoDao(wordsInfoDaoConfig, this);
        dingEJJBLDao = new DingEJJBLDao(dingEJJBLDaoConfig, this);
        feiYongZCDao = new FeiYongZCDao(feiYongZCDaoConfig, this);
        shuiLiangFTXXDao = new ShuiLiangFTXXDao(shuiLiangFTXXDaoConfig, this);
        jianHaoMXDao = new JianHaoMXDao(jianHaoMXDaoConfig, this);
        reXianGDDao = new ReXianGDDao(reXianGDDaoConfig, this);
        jianHaoDao = new JianHaoDao(jianHaoDaoConfig, this);
        chaoBiaoZTDao = new ChaoBiaoZTDao(chaoBiaoZTDaoConfig, this);
        chaoBiaoZTFLDao = new ChaoBiaoZTFLDao(chaoBiaoZTFLDaoConfig, this);
        duoMeiTXXDao = new DuoMeiTXXDao(duoMeiTXXDaoConfig, this);
        guiJiDao = new GuiJiDao(guiJiDaoConfig, this);
        neiFuBZDao = new NeiFuBZDao(neiFuBZDaoConfig, this);
        zhuangTaiLXCSDao = new ZhuangTaiLXCSDao(zhuangTaiLXCSDaoConfig, this);
        bIAOKAXXDao = new BIAOKAXXDao(bIAOKAXXDaoConfig, this);
        dengLuLSDao = new DengLuLSDao(dengLuLSDaoConfig, this);
        metaInfoDao = new MetaInfoDao(metaInfoDaoConfig, this);
        biaoWuGDDao = new BiaoWuGDDao(biaoWuGDDaoConfig, this);
        renwuXXDao = new RenwuXXDao(renwuXXDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);
        waiFuGDDetailDao = new WaiFuGDDetailDao(waiFuGDDetailDaoConfig, this);
        waiFuGDMainDao = new WaiFuGDMainDao(waiFuGDMainDaoConfig, this);
        waiFuYYDao = new WaiFuYYDao(waiFuYYDaoConfig, this);
        yanChiBiaoDao = new YanChiBiaoDao(yanChiBiaoDaoConfig, this);
        jiaoFeiXXDao = new JiaoFeiXXDao(jiaoFeiXXDaoConfig, this);
        gongGaoXXDao = new GongGaoXXDao(gongGaoXXDaoConfig, this);
        yuanGongXXDao = new YuanGongXXDao(yuanGongXXDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        jinEXXDao = new JinEXXDao(jinEXXDaoConfig, this);
        qianFeiXXDao = new QianFeiXXDao(qianFeiXXDaoConfig, this);
        rushPayRWDao = new RushPayRWDao(rushPayRWDaoconfig,this);
        jiChaRWDao = new JiChaRWDao(jiChaRWDaoconfig,this);
        jiChaSJDao = new JiChaSJDao(jiChaSJDaoconfig,this);
        waiFuCBSJDao =  new WaiFuCBSJDao(waiFuCBSJDaoConfig, this);
        biaoKaBeanDao =  new BiaoKaBeanDao(biaoKaBeanDaoConfig, this);
        biaoKaListBeanDao =  new BiaoKaListBeanDao(biaoKaListBeanDaoConfig, this);
        biaoKaWholeEntityDao = new BiaoKaWholeEntityDao(biaoKaWholeEntityDaoConfig, this);
        xunJianTaskBeanDao = new XunJianTaskBeanDao(xunJianTaskBeanDaoConfig, this);


        registerDao(ChaoBiaoRW.class, chaoBiaoRWDao);
        registerDao(ChaoBiaoSJ.class, chaoBiaoSJDao);
        registerDao(ChaoBiaoBZ.class, chaoBiaoBZDao);
        registerDao(ChaoBiaoGJ.class, chaoBiaoGJDao);
        registerDao(ChaoBiaoJL.class, chaoBiaoJLDao);
        registerDao(HuanBiaoJL.class, huanBiaoJLDao);
        registerDao(CiYuXX.class, ciYuXXDao);
        registerDao(XinXiBG.class, xinXiBGDao);
        registerDao(FeiYongZKL.class, feiYongZKLDao);
        registerDao(WordsInfo.class, wordsInfoDao);
        registerDao(DingEJJBL.class, dingEJJBLDao);
        registerDao(FeiYongZC.class, feiYongZCDao);
        registerDao(ShuiLiangFTXX.class, shuiLiangFTXXDao);
        registerDao(JianHaoMX.class, jianHaoMXDao);
        registerDao(ReXianGD.class, reXianGDDao);
        registerDao(JianHao.class, jianHaoDao);
        registerDao(ChaoBiaoRW.class, chaoBiaoRWDao);
        registerDao(ChaoBiaoSJ.class, chaoBiaoSJDao);
        registerDao(ChaoBiaoZT.class, chaoBiaoZTDao);
        registerDao(ChaoBiaoZTFL.class, chaoBiaoZTFLDao);
        registerDao(DuoMeiTXX.class, duoMeiTXXDao);
        registerDao(GuiJi.class, guiJiDao);
        registerDao(NeiFuBZ.class, neiFuBZDao);
        registerDao(ZhuangTaiLXCS.class, zhuangTaiLXCSDao);
        registerDao(BIAOKAXX.class, bIAOKAXXDao);
        registerDao(DengLuLS.class, dengLuLSDao);
        registerDao(MetaInfo.class, metaInfoDao);
        registerDao(BiaoWuGD.class, biaoWuGDDao);
        registerDao(RenwuXX.class, renwuXXDao);
        registerDao(Users.class, usersDao);
        registerDao(WaiFuGDDetail.class, waiFuGDDetailDao);
        registerDao(WaiFuGDMain.class, waiFuGDMainDao);
        registerDao(WaiFuYY.class, waiFuYYDao);
        registerDao(YanChiBiao.class, yanChiBiaoDao);
        registerDao(JiaoFeiXX.class, jiaoFeiXXDao);
        registerDao(GongGaoXX.class, gongGaoXXDao);
        registerDao(YuanGongXX.class, yuanGongXXDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(JinEXX.class, jinEXXDao);
        registerDao(QianFeiXX.class, qianFeiXXDao);
        registerDao(RushPayRW.class,rushPayRWDao);
        registerDao(JiChaRW.class,jiChaRWDao);
        registerDao(JiChaSJ.class,jiChaSJDao);
        registerDao(WaiFuCBSJ.class,waiFuCBSJDao);
        registerDao(BiaoKaBean.class,biaoKaBeanDao);
        registerDao(BiaoKaListBean.class,biaoKaListBeanDao);
        registerDao(BiaoKaWholeEntity.class,biaoKaWholeEntityDao);
        registerDao(XunJianTaskBean.class,xunJianTaskBeanDao);


    }
    
    public void clear() {
        chaoBiaoRWDaoConfig.getIdentityScope().clear();
        chaoBiaoSJDaoConfig.getIdentityScope().clear();
        chaoBiaoBZDaoConfig.getIdentityScope().clear();
        chaoBiaoGJDaoConfig.getIdentityScope().clear();
        chaoBiaoJLDaoConfig.getIdentityScope().clear();
        huanBiaoJLDaoConfig.getIdentityScope().clear();
        ciYuXXDaoConfig.getIdentityScope().clear();
        xinXiBGDaoConfig.getIdentityScope().clear();
        feiYongZKLDaoConfig.getIdentityScope().clear();
        wordsInfoDaoConfig.getIdentityScope().clear();
        dingEJJBLDaoConfig.getIdentityScope().clear();
        feiYongZCDaoConfig.getIdentityScope().clear();
        shuiLiangFTXXDaoConfig.getIdentityScope().clear();
        jianHaoMXDaoConfig.getIdentityScope().clear();
        reXianGDDaoConfig.getIdentityScope().clear();
        jianHaoDaoConfig.getIdentityScope().clear();
        chaoBiaoSJDaoConfig.getIdentityScope().clear();
        chaoBiaoZTDaoConfig.getIdentityScope().clear();
        chaoBiaoZTFLDaoConfig.getIdentityScope().clear();
        duoMeiTXXDaoConfig.getIdentityScope().clear();
        guiJiDaoConfig.getIdentityScope().clear();
        neiFuBZDaoConfig.getIdentityScope().clear();
        zhuangTaiLXCSDaoConfig.getIdentityScope().clear();
        bIAOKAXXDaoConfig.getIdentityScope().clear();
        dengLuLSDaoConfig.getIdentityScope().clear();
        metaInfoDaoConfig.getIdentityScope().clear();
        biaoWuGDDaoConfig.getIdentityScope().clear();
        renwuXXDaoConfig.getIdentityScope().clear();
        usersDaoConfig.getIdentityScope().clear();
        waiFuGDDetailDaoConfig.getIdentityScope().clear();
        waiFuGDMainDaoConfig.getIdentityScope().clear();
        waiFuYYDaoConfig.getIdentityScope().clear();
        yanChiBiaoDaoConfig.getIdentityScope().clear();
        jiaoFeiXXDaoConfig.getIdentityScope().clear();
        gongGaoXXDaoConfig.getIdentityScope().clear();
        yuanGongXXDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
        jinEXXDaoConfig.getIdentityScope().clear();
        qianFeiXXDaoConfig.getIdentityScope().clear();
        rushPayRWDaoconfig.getIdentityScope().clear();
        jiChaRWDaoconfig.getIdentityScope().clear();
        jiChaSJDaoconfig.getIdentityScope().clear();
        waiFuCBSJDaoConfig.getIdentityScope().clear();
        biaoKaBeanDaoConfig.getIdentityScope().clear();
        biaoKaListBeanDaoConfig.getIdentityScope().clear();
        biaoKaWholeEntityDaoConfig.getIdentityScope().clear();
        xunJianTaskBeanDaoConfig.getIdentityScope().clear();

    }

//    public void clearChaoBiaoRWMemory(){
//        chaoBiaoRWDaoConfig.getIdentityScope().clear();
//    }


    public ChaoBiaoBZDao getChaoBiaoBZDao() {
        return chaoBiaoBZDao;
    }

    public ChaoBiaoGJDao getChaoBiaoGJDao() {
        return chaoBiaoGJDao;
    }

    public ChaoBiaoJLDao getChaoBiaoJLDao() {
        return chaoBiaoJLDao;
    }

    public HuanBiaoJLDao getHuanBiaoJLDao() {
        return huanBiaoJLDao;
    }

    public CiYuXXDao getCiYuXXDao() {
        return ciYuXXDao;
    }

    public XinXiBGDao getXinXiBGDao() {
        return xinXiBGDao;
    }

    public FeiYongZKLDao getFeiYongZKLDao() {
        return feiYongZKLDao;
    }

    public WordsInfoDao getWordsInfoDao() {
        return wordsInfoDao;
    }

    public DingEJJBLDao getDingEJJBLDao() {
        return dingEJJBLDao;
    }

    public FeiYongZCDao getFeiYongZCDao() {
        return feiYongZCDao;
    }

    public ShuiLiangFTXXDao getShuiLiangFTXXDao() {
        return shuiLiangFTXXDao;
    }

    public JianHaoMXDao getJianHaoMXDao() {
        return jianHaoMXDao;
    }

    public ReXianGDDao getReXianGDDao() {
        return reXianGDDao;
    }

    public JianHaoDao getJianHaoDao() {
        return jianHaoDao;
    }

    public ChaoBiaoRWDao getChaoBiaoRWDao() {
        return chaoBiaoRWDao;
    }

    public ChaoBiaoSJDao getChaoBiaoSJDao() {
        return chaoBiaoSJDao;
    }

    public ChaoBiaoZTDao getChaoBiaoZTDao() {
        return chaoBiaoZTDao;
    }

    public ChaoBiaoZTFLDao getChaoBiaoZTFLDao() {
        return chaoBiaoZTFLDao;
    }

    public DuoMeiTXXDao getDuoMeiTXXDao() {
        return duoMeiTXXDao;
    }

    public GuiJiDao getGuiJiDao() {
        return guiJiDao;
    }

    public NeiFuBZDao getNeiFuBZDao() {
        return neiFuBZDao;
    }

    public ZhuangTaiLXCSDao getZhuangTaiLXCSDao() {
        return zhuangTaiLXCSDao;
    }

    public BIAOKAXXDao getBIAOKAXXDao() {
        return bIAOKAXXDao;
    }

    public DengLuLSDao getDengLuLSDao() {
        return dengLuLSDao;
    }

    public MetaInfoDao getMetaInfoDao() {
        return metaInfoDao;
    }

    public BiaoWuGDDao getBiaoWuGDDao() {
        return biaoWuGDDao;
    }

    public RenwuXXDao getRenwuXXDao() {
        return renwuXXDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public WaiFuGDDetailDao getWaiFuGDDetailDao() {
        return waiFuGDDetailDao;
    }

    public WaiFuGDMainDao getWaiFuGDMainDao() {
        return waiFuGDMainDao;
    }

    public WaiFuYYDao getWaiFuYYDao() {
        return waiFuYYDao;
    }

    public YanChiBiaoDao getYanChiBiaoDao() {
        return yanChiBiaoDao;
    }

    public JiaoFeiXXDao getJiaoFeiXXDao() {
        return jiaoFeiXXDao;
    }

    public GongGaoXXDao getGongGaoXXDao() {
        return gongGaoXXDao;
    }

    public YuanGongXXDao getYuanGongXXDao() {
        return yuanGongXXDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public JinEXXDao getJinEXXDao() {
        return jinEXXDao;
    }

    public QianFeiXXDao getQianFeiXXDao() {
        return qianFeiXXDao;
    }

    public RushPayRWDao getRushPayRWDao(){
        return rushPayRWDao;
    }

    public JiChaRWDao getJiChaRWDao() {
        return jiChaRWDao;
    }

    public JiChaSJDao getJiChaSJDao() {
        return jiChaSJDao;
    }

    public WaiFuCBSJDao getWaiFuCBSJDao(){
        return waiFuCBSJDao;
    }

    public BiaoKaBeanDao getBiaoKaBeanDao(){
      return biaoKaBeanDao;
    }

    public BiaoKaListBeanDao getBiaoKaListBeanDao(){
    return biaoKaListBeanDao;
  }

    public BiaoKaWholeEntityDao getBiaoKaWholeEntityDao(){
    return biaoKaWholeEntityDao;
  }

    public XunJianTaskBeanDao getXunJianTaskBeanDao(){
    return xunJianTaskBeanDao;
  }
}
