package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table KG_BIAOKAXX.
 */
public class BIAOKAXX {
    public static final int CHAOBIAO_BIAOKAXX = 0;
    public static final int SAMPLING_BIAOKAXX = 1;
    public static final int NEW_BIAOKAXX = 2;
    public static final int OUT_BIAOKAXX = 3;
    public static final int DELAY = 4;

    private int ID;
    /**
     * Not-null value.
     */
    private String S_CH;
    private int I_CENEIXH;
    /**
     * Not-null value.
     */
    private String S_CID;
    /**
     * Not-null value.
     */
    private String S_KEHUBH;
    /**
     * Not-null value.
     */
    private String S_KeHuMC;
    /**
     * Not-null value.
     */
    private String S_ST;
    /**
     * Not-null value.
     */
    private String S_DiZhi;
    private String S_LIANXIR;
    private String S_LIANXISJ;
    private String S_LIANXIDH;
    private String S_ShouFeiFS;
    private String S_YinHangMC;
    /**
     * Not-null value.
     */
    private String S_JianHao;
    private String S_JianHaoMC;
    private int I_YongHuZT;
    private long D_LIHU;
    private String S_BiaoWei;
    private String S_SHUIBIAOGYH;
    private String S_SHUIBIAOTXM;
    private String S_KOUJINGMC;
    private int I_LIANGCHENG;
    private String S_BIAOXING;
    private String S_SHUIBIAOCJ;
    private int I_ShuiBiaoFL;
    private String S_ShuiBiaoFLMC;
    private int I_SHUIBIAOBL;
    private String S_KaiZhangFL;
    private int I_GONGNENGFL;
    private int I_ShiFouJHYS;
    private int I_ShiFouShouLJF;
    private double N_LaJiFeiXS;
    private int I_ShiFouShouWYJ;
    private int I_ShiFouDEJJ;
    private int I_DINGESL;
    private String S_ZONGBIAOBH;
    private long D_ZHUANGBIAORQ;
    private long D_HUANBIAORQ;
    private int I_XINBIAODM;
    private int I_JIUBIAOCM;
    private String S_X1;
    private String S_Y1;
    private String S_X;
    private String S_Y;
    private int I_FENTANFS;
    private int I_FENTANL;
    private double N_YuCunKYE;
    private int I_QianFeiZBS;
    private double N_QianFeiZJE;
    private String S_BEIZHU;
    private int I_SHUIBIAOZT;
    private double N_RENKOUS;
    private int I_DIBAOYHSL;
    private int I_GONGCEYHSL;
    private double N_YONGSHUIZKL;
    private double N_PAISHUIZKL;
    private double N_ZHEKOUL1;
    private double N_ZHEKOUL2;
    private double N_ZHEKOUL3;
    private int I_ERCIGS;
    private int I_DIANZIZD;
    private String S_XINGZHENGQ;
    private String S_BIAOKAZT;
    private String S_SHESHUIID;
    private double N_JIAGE;
    private String S_SHUIBIAOLXBH;
    private double N_ZIZHUANGBKZXS;
    private String S_SHUIBIAOZL;
    private String S_SHUIBIAOFL;
    private String S_YUANCHUANID;
    private String S_ZHONGDUANH;
    private String S_YUANCHUANCJ;
    private String S_DUORENKFA;
    private int I_SHIFOUJT;
    private long D_DUORENKJZ;
    private int D_GONGSHUIHTNX;
    private String S_FANGDONGDH;
    private String S_FANGKEDH;
    private int I_NIANLEIJ;
    private int I_HUANBIAO;
    private int I_QIANFEI;

    public BIAOKAXX() {
    }

    public BIAOKAXX(int ID,
                    String S_CH,
                    int I_CENEIXH,
                    String S_CID,
                    String S_KEHUBH,
                    String S_KeHuMC,
                    String S_ST,
                    String S_DiZhi,
                    String S_LIANXIR,
                    String S_LIANXISJ,
                    String S_LIANXIDH,
                    String S_ShouFeiFS,
                    String S_YinHangMC,
                    String S_JianHao,
                    String S_JianHaoMC,
                    int I_YongHuZT,
                    long D_LIHU,
                    String S_BiaoWei,
                    String S_SHUIBIAOGYH,
                    String S_SHUIBIAOTXM,
                    String S_KOUJINGMC,
                    int I_LIANGCHENG,
                    String S_BIAOXING,
                    String S_SHUIBIAOCJ,
                    int I_ShuiBiaoFL,
                    String S_ShuiBiaoFLMC,
                    int I_SHUIBIAOBL,
                    String S_KaiZhangFL,
                    int I_GONGNENGFL,
                    int I_ShiFouJHYS,
                    int I_ShiFouShouLJF,
                    double N_LaJiFeiXS,
                    int I_ShiFouShouWYJ,
                    int I_ShiFouDEJJ,
                    int I_DINGESL,
                    String S_ZONGBIAOBH,
                    long D_ZHUANGBIAORQ,
                    long D_HUANBIAORQ,
                    int I_XINBIAODM,
                    int I_JIUBIAOCM,
                    String S_X1,
                    String S_Y1,
                    String S_X,
                    String S_Y,
                    int I_FENTANFS,
                    int I_FENTANL,
                    double N_YuCunKYE,
                    int I_QianFeiZBS,
                    double N_QianFeiZJE,
                    String S_BEIZHU,
                    int I_SHUIBIAOZT,
                    double N_RENKOUS,
                    int I_DIBAOYHSL,
                    int I_GONGCEYHSL,
                    double N_YONGSHUIZKL,
                    double N_PAISHUIZKL,
                    double N_ZHEKOUL1,
                    double N_ZHEKOUL2,
                    double N_ZHEKOUL3,
                    int I_ERCIGS,
                    int I_DIANZIZD,
                    String S_XINGZHENGQ,
                    String S_BIAOKAZT,
                    String S_SHESHUIID,
                    double N_JIAGE,
                    String S_SHUIBIAOLXBH,
                    double N_ZIZHUANGBKZXS,
                    String S_SHUIBIAOZL,
                    String S_SHUIBIAOFL,
                    String S_YUANCHUANID,
                    String S_ZHONGDUANH,
                    String S_YUANCHUANCJ,
                    String S_DUORENKFA,
                    int I_SHIFOUJT,
                    long D_DUORENKJZ,
                    int D_GONGSHUIHTNX,
                    String S_FANGDONGDH,
                    String S_FANGKEDH,
                    int I_NIANLEIJ,
                    int I_HUANBIAO,
                    int I_QIANFEI) {
        this.ID = ID;
        this.S_CH = S_CH;
        this.I_CENEIXH = I_CENEIXH;
        this.S_CID = S_CID;
        this.S_KEHUBH = S_KEHUBH;
        this.S_KeHuMC = S_KeHuMC;
        this.S_ST = S_ST;
        this.S_DiZhi = S_DiZhi;
        this.S_LIANXIR = S_LIANXIR;
        this.S_LIANXISJ = S_LIANXISJ;
        this.S_LIANXIDH = S_LIANXIDH;
        this.S_ShouFeiFS = S_ShouFeiFS;
        this.S_YinHangMC = S_YinHangMC;
        this.S_JianHao = S_JianHao;
        this.S_JianHaoMC = S_JianHaoMC;
        this.I_YongHuZT = I_YongHuZT;
        this.D_LIHU = D_LIHU;
        this.S_BiaoWei = S_BiaoWei;
        this.S_SHUIBIAOGYH = S_SHUIBIAOGYH;
        this.S_SHUIBIAOTXM = S_SHUIBIAOTXM;
        this.S_KOUJINGMC = S_KOUJINGMC;
        this.I_LIANGCHENG = I_LIANGCHENG;
        this.S_BIAOXING = S_BIAOXING;
        this.S_SHUIBIAOCJ = S_SHUIBIAOCJ;
        this.I_ShuiBiaoFL = I_ShuiBiaoFL;
        this.S_ShuiBiaoFLMC = S_ShuiBiaoFLMC;
        this.I_SHUIBIAOBL = I_SHUIBIAOBL;
        this.S_KaiZhangFL = S_KaiZhangFL;
        this.I_GONGNENGFL = I_GONGNENGFL;
        this.I_ShiFouJHYS = I_ShiFouJHYS;
        this.I_ShiFouShouLJF = I_ShiFouShouLJF;
        this.N_LaJiFeiXS = N_LaJiFeiXS;
        this.I_ShiFouShouWYJ = I_ShiFouShouWYJ;
        this.I_ShiFouDEJJ = I_ShiFouDEJJ;
        this.I_DINGESL = I_DINGESL;
        this.S_ZONGBIAOBH = S_ZONGBIAOBH;
        this.D_ZHUANGBIAORQ = D_ZHUANGBIAORQ;
        this.D_HUANBIAORQ = D_HUANBIAORQ;
        this.I_XINBIAODM = I_XINBIAODM;
        this.I_JIUBIAOCM = I_JIUBIAOCM;
        this.S_X1 = S_X1;
        this.S_Y1 = S_Y1;
        this.S_X = S_X;
        this.S_Y = S_Y;
        this.I_FENTANFS = I_FENTANFS;
        this.I_FENTANL = I_FENTANL;
        this.N_YuCunKYE = N_YuCunKYE;
        this.I_QianFeiZBS = I_QianFeiZBS;
        this.N_QianFeiZJE = N_QianFeiZJE;
        this.S_BEIZHU = S_BEIZHU;
        this.I_SHUIBIAOZT = I_SHUIBIAOZT;
        this.N_RENKOUS = N_RENKOUS;
        this.I_DIBAOYHSL = I_DIBAOYHSL;
        this.I_GONGCEYHSL = I_GONGCEYHSL;
        this.N_YONGSHUIZKL = N_YONGSHUIZKL;
        this.N_PAISHUIZKL = N_PAISHUIZKL;
        this.N_ZHEKOUL1 = N_ZHEKOUL1;
        this.N_ZHEKOUL2 = N_ZHEKOUL2;
        this.N_ZHEKOUL3 = N_ZHEKOUL3;
        this.I_ERCIGS = I_ERCIGS;
        this.I_DIANZIZD = I_DIANZIZD;
        this.S_XINGZHENGQ = S_XINGZHENGQ;
        this.S_BIAOKAZT = S_BIAOKAZT;
        this.S_SHESHUIID = S_SHESHUIID;
        this.N_JIAGE = N_JIAGE;
        this.S_SHUIBIAOLXBH = S_SHUIBIAOLXBH;
        this.N_ZIZHUANGBKZXS = N_ZIZHUANGBKZXS;
        this.S_SHUIBIAOZL = S_SHUIBIAOZL;
        this.S_SHUIBIAOFL = S_SHUIBIAOFL;
        this.S_YUANCHUANID = S_YUANCHUANID;
        this.S_ZHONGDUANH = S_ZHONGDUANH;
        this.S_YUANCHUANCJ = S_YUANCHUANCJ;
        this.S_DUORENKFA = S_DUORENKFA;
        this.I_SHIFOUJT = I_SHIFOUJT;
        this.D_DUORENKJZ = D_DUORENKJZ;
        this.D_GONGSHUIHTNX = D_GONGSHUIHTNX;
        this.S_FANGDONGDH = S_FANGDONGDH;
        this.S_FANGKEDH = S_FANGKEDH;
        this.I_NIANLEIJ = I_NIANLEIJ;
        this.I_HUANBIAO = I_HUANBIAO;
        this.I_QIANFEI = I_QIANFEI;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    /**
     * Not-null value.
     */
    public String getS_CH() {
        return S_CH;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setS_CH(String S_CH) {
        this.S_CH = S_CH;
    }

    public int getI_CENEIXH() {
        return I_CENEIXH;
    }

    public void setI_CENEIXH(int I_CENEIXH) {
        this.I_CENEIXH = I_CENEIXH;
    }

    /**
     * Not-null value.
     */
    public String getS_CID() {
        return S_CID;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setS_CID(String S_CID) {
        this.S_CID = S_CID;
    }

    /**
     * Not-null value.
     */
    public String getS_KEHUBH() {
        return S_KEHUBH;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setS_KEHUBH(String S_KEHUBH) {
        this.S_KEHUBH = S_KEHUBH;
    }

    /**
     * Not-null value.
     */
    public String getS_KeHuMC() {
        return S_KeHuMC;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setS_KeHuMC(String S_KeHuMC) {
        this.S_KeHuMC = S_KeHuMC;
    }

    /**
     * Not-null value.
     */
    public String getS_ST() {
        return S_ST;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setS_ST(String S_ST) {
        this.S_ST = S_ST;
    }

    /**
     * Not-null value.
     */
    public String getS_DiZhi() {
        return S_DiZhi;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setS_DiZhi(String S_DiZhi) {
        this.S_DiZhi = S_DiZhi;
    }

    public String getS_LIANXIR() {
        return S_LIANXIR;
    }

    public void setS_LIANXIR(String S_LIANXIR) {
        this.S_LIANXIR = S_LIANXIR;
    }

    public String getS_LIANXISJ() {
        return S_LIANXISJ;
    }

    public void setS_LIANXISJ(String S_LIANXISJ) {
        this.S_LIANXISJ = S_LIANXISJ;
    }

    public String getS_LIANXIDH() {
        return S_LIANXIDH;
    }

    public void setS_LIANXIDH(String S_LIANXIDH) {
        this.S_LIANXIDH = S_LIANXIDH;
    }

    public String getS_ShouFeiFS() {
        return S_ShouFeiFS;
    }

    public void setS_ShouFeiFS(String S_ShouFeiFS) {
        this.S_ShouFeiFS = S_ShouFeiFS;
    }

    public String getS_YinHangMC() {
        return S_YinHangMC;
    }

    public void setS_YinHangMC(String S_YinHangMC) {
        this.S_YinHangMC = S_YinHangMC;
    }

    /**
     * Not-null value.
     */
    public String getS_JianHao() {
        return S_JianHao;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setS_JianHao(String S_JianHao) {
        this.S_JianHao = S_JianHao;
    }

    public String getS_JianHaoMC() {
        return S_JianHaoMC;
    }

    public void setS_JianHaoMC(String S_JianHaoMC) {
        this.S_JianHaoMC = S_JianHaoMC;
    }

    public int getI_YongHuZT() {
        return I_YongHuZT;
    }

    public void setI_YongHuZT(int I_YongHuZT) {
        this.I_YongHuZT = I_YongHuZT;
    }

    public long getD_LIHU() {
        return D_LIHU;
    }

    public void setD_LIHU(long D_LIHU) {
        this.D_LIHU = D_LIHU;
    }

    public String getS_BiaoWei() {
        return S_BiaoWei;
    }

    public void setS_BiaoWei(String S_BiaoWei) {
        this.S_BiaoWei = S_BiaoWei;
    }

    public String getS_SHUIBIAOGYH() {
        return S_SHUIBIAOGYH;
    }

    public void setS_SHUIBIAOGYH(String S_SHUIBIAOGYH) {
        this.S_SHUIBIAOGYH = S_SHUIBIAOGYH;
    }

    public String getS_SHUIBIAOTXM() {
        return S_SHUIBIAOTXM;
    }

    public void setS_SHUIBIAOTXM(String S_SHUIBIAOTXM) {
        this.S_SHUIBIAOTXM = S_SHUIBIAOTXM;
    }

    public String getS_KOUJINGMC() {
        return S_KOUJINGMC;
    }

    public void setS_KOUJINGMC(String S_KOUJINGMC) {
        this.S_KOUJINGMC = S_KOUJINGMC;
    }

    public int getI_LIANGCHENG() {
        return I_LIANGCHENG;
    }

    public void setI_LIANGCHENG(int I_LIANGCHENG) {
        this.I_LIANGCHENG = I_LIANGCHENG;
    }

    public String getS_BIAOXING() {
        return S_BIAOXING;
    }

    public void setS_BIAOXING(String S_BIAOXING) {
        this.S_BIAOXING = S_BIAOXING;
    }

    public String getS_SHUIBIAOCJ() {
        return S_SHUIBIAOCJ;
    }

    public void setS_SHUIBIAOCJ(String S_SHUIBIAOCJ) {
        this.S_SHUIBIAOCJ = S_SHUIBIAOCJ;
    }

    public int getI_ShuiBiaoFL() {
        return I_ShuiBiaoFL;
    }

    public void setI_ShuiBiaoFL(int I_ShuiBiaoFL) {
        this.I_ShuiBiaoFL = I_ShuiBiaoFL;
    }

    public String getS_ShuiBiaoFLMC() {
        return S_ShuiBiaoFLMC;
    }

    public void setS_ShuiBiaoFLMC(String S_ShuiBiaoFLMC) {
        this.S_ShuiBiaoFLMC = S_ShuiBiaoFLMC;
    }

    public int getI_SHUIBIAOBL() {
        return I_SHUIBIAOBL;
    }

    public void setI_SHUIBIAOBL(int I_SHUIBIAOBL) {
        this.I_SHUIBIAOBL = I_SHUIBIAOBL;
    }

    public String getS_KaiZhangFL() {
        return S_KaiZhangFL;
    }

    public void setS_KaiZhangFL(String S_KaiZhangFL) {
        this.S_KaiZhangFL = S_KaiZhangFL;
    }

    public int getI_GONGNENGFL() {
        return I_GONGNENGFL;
    }

    public void setI_GONGNENGFL(int I_GONGNENGFL) {
        this.I_GONGNENGFL = I_GONGNENGFL;
    }

    public int getI_ShiFouJHYS() {
        return I_ShiFouJHYS;
    }

    public void setI_ShiFouJHYS(int I_ShiFouJHYS) {
        this.I_ShiFouJHYS = I_ShiFouJHYS;
    }

    public int getI_ShiFouShouLJF() {
        return I_ShiFouShouLJF;
    }

    public void setI_ShiFouShouLJF(int I_ShiFouShouLJF) {
        this.I_ShiFouShouLJF = I_ShiFouShouLJF;
    }

    public double getN_LaJiFeiXS() {
        return N_LaJiFeiXS;
    }

    public void setN_LaJiFeiXS(double N_LaJiFeiXS) {
        this.N_LaJiFeiXS = N_LaJiFeiXS;
    }

    public int getI_ShiFouShouWYJ() {
        return I_ShiFouShouWYJ;
    }

    public void setI_ShiFouShouWYJ(int I_ShiFouShouWYJ) {
        this.I_ShiFouShouWYJ = I_ShiFouShouWYJ;
    }

    public int getI_ShiFouDEJJ() {
        return I_ShiFouDEJJ;
    }

    public void setI_ShiFouDEJJ(int I_ShiFouDEJJ) {
        this.I_ShiFouDEJJ = I_ShiFouDEJJ;
    }

    public int getI_DINGESL() {
        return I_DINGESL;
    }

    public void setI_DINGESL(int I_DINGESL) {
        this.I_DINGESL = I_DINGESL;
    }

    public String getS_ZONGBIAOBH() {
        return S_ZONGBIAOBH;
    }

    public void setS_ZONGBIAOBH(String S_ZONGBIAOBH) {
        this.S_ZONGBIAOBH = S_ZONGBIAOBH;
    }

    public long getD_ZHUANGBIAORQ() {
        return D_ZHUANGBIAORQ;
    }

    public void setD_ZHUANGBIAORQ(long D_ZHUANGBIAORQ) {
        this.D_ZHUANGBIAORQ = D_ZHUANGBIAORQ;
    }

    public long getD_HUANBIAORQ() {
        return D_HUANBIAORQ;
    }

    public void setD_HUANBIAORQ(long D_HUANBIAORQ) {
        this.D_HUANBIAORQ = D_HUANBIAORQ;
    }

    public int getI_XINBIAODM() {
        return I_XINBIAODM;
    }

    public void setI_XINBIAODM(int I_XINBIAODM) {
        this.I_XINBIAODM = I_XINBIAODM;
    }

    public int getI_JIUBIAOCM() {
        return I_JIUBIAOCM;
    }

    public void setI_JIUBIAOCM(int I_JIUBIAOCM) {
        this.I_JIUBIAOCM = I_JIUBIAOCM;
    }

    public String getS_X1() {
        return S_X1;
    }

    public void setS_X1(String S_X1) {
        this.S_X1 = S_X1;
    }

    public String getS_Y1() {
        return S_Y1;
    }

    public void setS_Y1(String S_Y1) {
        this.S_Y1 = S_Y1;
    }

    public String getS_X() {
        return S_X;
    }

    public void setS_X(String S_X) {
        this.S_X = S_X;
    }

    public String getS_Y() {
        return S_Y;
    }

    public void setS_Y(String S_Y) {
        this.S_Y = S_Y;
    }

    public int getI_FENTANFS() {
        return I_FENTANFS;
    }

    public void setI_FENTANFS(int I_FENTANFS) {
        this.I_FENTANFS = I_FENTANFS;
    }

    public int getI_FENTANL() {
        return I_FENTANL;
    }

    public void setI_FENTANL(int I_FENTANL) {
        this.I_FENTANL = I_FENTANL;
    }

    public double getN_YuCunKYE() {
        return N_YuCunKYE;
    }

    public void setN_YuCunKYE(double N_YuCunKYE) {
        this.N_YuCunKYE = N_YuCunKYE;
    }

    public int getI_QianFeiZBS() {
        return I_QianFeiZBS;
    }

    public void setI_QianFeiZBS(int I_QianFeiZBS) {
        this.I_QianFeiZBS = I_QianFeiZBS;
    }

    public double getN_QianFeiZJE() {
        return N_QianFeiZJE;
    }

    public void setN_QianFeiZJE(double N_QianFeiZJE) {
        this.N_QianFeiZJE = N_QianFeiZJE;
    }

    public String getS_BEIZHU() {
        return S_BEIZHU;
    }

    public void setS_BEIZHU(String S_BEIZHU) {
        this.S_BEIZHU = S_BEIZHU;
    }

    public int getI_SHUIBIAOZT() {
        return I_SHUIBIAOZT;
    }

    public void setI_SHUIBIAOZT(int I_SHUIBIAOZT) {
        this.I_SHUIBIAOZT = I_SHUIBIAOZT;
    }

    public double getN_RENKOUS() {
        return N_RENKOUS;
    }

    public void setN_RENKOUS(double N_RENKOUS) {
        this.N_RENKOUS = N_RENKOUS;
    }

    public int getI_DIBAOYHSL() {
        return I_DIBAOYHSL;
    }

    public void setI_DIBAOYHSL(int I_DIBAOYHSL) {
        this.I_DIBAOYHSL = I_DIBAOYHSL;
    }

    public int getI_GONGCEYHSL() {
        return I_GONGCEYHSL;
    }

    public void setI_GONGCEYHSL(int I_GONGCEYHSL) {
        this.I_GONGCEYHSL = I_GONGCEYHSL;
    }

    public double getN_YONGSHUIZKL() {
        return N_YONGSHUIZKL;
    }

    public void setN_YONGSHUIZKL(double N_YONGSHUIZKL) {
        this.N_YONGSHUIZKL = N_YONGSHUIZKL;
    }

    public double getN_PAISHUIZKL() {
        return N_PAISHUIZKL;
    }

    public void setN_PAISHUIZKL(double N_PAISHUIZKL) {
        this.N_PAISHUIZKL = N_PAISHUIZKL;
    }

    public double getN_ZHEKOUL1() {
        return N_ZHEKOUL1;
    }

    public void setN_ZHEKOUL1(double N_ZHEKOUL1) {
        this.N_ZHEKOUL1 = N_ZHEKOUL1;
    }

    public double getN_ZHEKOUL2() {
        return N_ZHEKOUL2;
    }

    public void setN_ZHEKOUL2(double N_ZHEKOUL2) {
        this.N_ZHEKOUL2 = N_ZHEKOUL2;
    }

    public double getN_ZHEKOUL3() {
        return N_ZHEKOUL3;
    }

    public void setN_ZHEKOUL3(double N_ZHEKOUL3) {
        this.N_ZHEKOUL3 = N_ZHEKOUL3;
    }

    public int getI_ERCIGS() {
        return I_ERCIGS;
    }

    public void setI_ERCIGS(int I_ERCIGS) {
        this.I_ERCIGS = I_ERCIGS;
    }

    public int getI_DIANZIZD() {
        return I_DIANZIZD;
    }

    public void setI_DIANZIZD(int I_DIANZIZD) {
        this.I_DIANZIZD = I_DIANZIZD;
    }

    public String getS_XINGZHENGQ() {
        return S_XINGZHENGQ;
    }

    public void setS_XINGZHENGQ(String S_XINGZHENGQ) {
        this.S_XINGZHENGQ = S_XINGZHENGQ;
    }

    public String getS_BIAOKAZT() {
        return S_BIAOKAZT;
    }

    public void setS_BIAOKAZT(String S_BIAOKAZT) {
        this.S_BIAOKAZT = S_BIAOKAZT;
    }

    public String getS_SHESHUIID() {
        return S_SHESHUIID;
    }

    public void setS_SHESHUIID(String S_SHESHUIID) {
        this.S_SHESHUIID = S_SHESHUIID;
    }

    public double getN_JIAGE() {
        return N_JIAGE;
    }

    public void setN_JIAGE(double N_JIAGE) {
        this.N_JIAGE = N_JIAGE;
    }

    public String getS_SHUIBIAOLXBH() {
        return S_SHUIBIAOLXBH;
    }

    public void setS_SHUIBIAOLXBH(String S_SHUIBIAOLXBH) {
        this.S_SHUIBIAOLXBH = S_SHUIBIAOLXBH;
    }

    public double getN_ZIZHUANGBKZXS() {
        return N_ZIZHUANGBKZXS;
    }

    public void setN_ZIZHUANGBKZXS(double N_ZIZHUANGBKZXS) {
        this.N_ZIZHUANGBKZXS = N_ZIZHUANGBKZXS;
    }

    public String getS_SHUIBIAOZL() {
        return S_SHUIBIAOZL;
    }

    public void setS_SHUIBIAOZL(String S_SHUIBIAOZL) {
        this.S_SHUIBIAOZL = S_SHUIBIAOZL;
    }

    public String getS_SHUIBIAOFL() {
        return S_SHUIBIAOFL;
    }

    public void setS_SHUIBIAOFL(String S_SHUIBIAOFL) {
        this.S_SHUIBIAOFL = S_SHUIBIAOFL;
    }

    public String getS_YUANCHUANID() {
        return S_YUANCHUANID;
    }

    public void setS_YUANCHUANID(String S_YUANCHUANID) {
        this.S_YUANCHUANID = S_YUANCHUANID;
    }

    public String getS_ZHONGDUANH() {
        return S_ZHONGDUANH;
    }

    public void setS_ZHONGDUANH(String S_ZHONGDUANH) {
        this.S_ZHONGDUANH = S_ZHONGDUANH;
    }

    public String getS_YUANCHUANCJ() {
        return S_YUANCHUANCJ;
    }

    public void setS_YUANCHUANCJ(String S_YUANCHUANCJ) {
        this.S_YUANCHUANCJ = S_YUANCHUANCJ;
    }

    public String getS_DUORENKFA() {
        return S_DUORENKFA;
    }

    public void setS_DUORENKFA(String S_DUORENKFA) {
        this.S_DUORENKFA = S_DUORENKFA;
    }

    public int getI_SHIFOUJT() {
        return I_SHIFOUJT;
    }

    public void setI_SHIFOUJT(int I_SHIFOUJT) {
        this.I_SHIFOUJT = I_SHIFOUJT;
    }

    public long getD_DUORENKJZ() {
        return D_DUORENKJZ;
    }

    public void setD_DUORENKJZ(long D_DUORENKJZ) {
        this.D_DUORENKJZ = D_DUORENKJZ;
    }

    public int getD_GONGSHUIHTNX() {
        return D_GONGSHUIHTNX;
    }

    public void setD_GONGSHUIHTNX(int D_GONGSHUIHTNX) {
        this.D_GONGSHUIHTNX = D_GONGSHUIHTNX;
    }

    public String getS_FANGDONGDH() {
        return S_FANGDONGDH;
    }

    public void setS_FANGDONGDH(String S_FANGDONGDH) {
        this.S_FANGDONGDH = S_FANGDONGDH;
    }

    public String getS_FANGKEDH() {
        return S_FANGKEDH;
    }

    public void setS_FANGKEDH(String S_FANGKEDH) {
        this.S_FANGKEDH = S_FANGKEDH;
    }

    public int getI_NIANLEIJ() {
        return I_NIANLEIJ;
    }

    public void setI_NIANLEIJ(int I_NIANLEIJ) {
        this.I_NIANLEIJ = I_NIANLEIJ;
    }

    public int getI_HUANBIAO() {
        return I_HUANBIAO;
    }

    public void setI_HUANBIAO(int I_HUANBIAO) {
        this.I_HUANBIAO = I_HUANBIAO;
    }

    public int getI_QIANFEI() {
        return I_QIANFEI;
    }

    public void setI_QIANFEI(int I_QIANFEI) {
        this.I_QIANFEI = I_QIANFEI;
    }

}
