package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CB_ChaoBiaoJL.
 */
public class ChaoBiaoJL {

    private long ID;
    /** Not-null value. */
    private String S_CID;
    private int I_CHAOBIAON;
    private int I_CHAOBIAOY;
    private int I_ChaoCi;
    private long D_ChaoBiaoRQ;
    private int I_ShangCiCM;
    private int I_BENCICM;
    private int I_CHAOJIANSL;
    private String S_CHAOBIAOZT;
    private String S_ChaoBiaoY;
    private String S_CHAOBIAOBZ;
    private int I_CHAOBIAOZTBM;
    private int I_LIANGGAOLDYYBM;

    public ChaoBiaoJL() {
    }

    public ChaoBiaoJL(long ID,
                      String S_CID,
                      int I_CHAOBIAON,
                      int I_CHAOBIAOY,
                      int I_ChaoCi,
                      long D_ChaoBiaoRQ,
                      int I_ShangCiCM,
                      int I_BENCICM,
                      int I_CHAOJIANSL,
                      String S_CHAOBIAOZT,
                      String S_ChaoBiaoY,
                      String S_CHAOBIAOBZ,
                      int I_CHAOBIAOZTBM,
                      int I_LIANGGAOLDYYBM) {
        this.ID = ID;
        this.S_CID = S_CID;
        this.I_CHAOBIAON = I_CHAOBIAON;
        this.I_CHAOBIAOY = I_CHAOBIAOY;
        this.I_ChaoCi = I_ChaoCi;
        this.D_ChaoBiaoRQ = D_ChaoBiaoRQ;
        this.I_ShangCiCM = I_ShangCiCM;
        this.I_BENCICM = I_BENCICM;
        this.I_CHAOJIANSL = I_CHAOJIANSL;
        this.S_CHAOBIAOZT = S_CHAOBIAOZT;
        this.S_ChaoBiaoY = S_ChaoBiaoY;
        this.S_CHAOBIAOBZ = S_CHAOBIAOBZ;
        this.I_CHAOBIAOZTBM = I_CHAOBIAOZTBM;
        this.I_LIANGGAOLDYYBM = I_LIANGGAOLDYYBM;
    }

    public long getID() {
        return ID;
    }

    public void setID(long ID) {
        this.ID = ID;
    }

    /** Not-null value. */
    public String getS_CID() {
        return S_CID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_CID(String S_CID) {
        this.S_CID = S_CID;
    }

    public int getI_CHAOBIAON() {
        return I_CHAOBIAON;
    }

    public void setI_CHAOBIAON(int I_CHAOBIAON) {
        this.I_CHAOBIAON = I_CHAOBIAON;
    }

    public int getI_CHAOBIAOY() {
        return I_CHAOBIAOY;
    }

    public void setI_CHAOBIAOY(int I_CHAOBIAOY) {
        this.I_CHAOBIAOY = I_CHAOBIAOY;
    }

    public int getI_ChaoCi() {
        return I_ChaoCi;
    }

    public void setI_ChaoCi(int I_ChaoCi) {
        this.I_ChaoCi = I_ChaoCi;
    }

    public long getD_ChaoBiaoRQ() {
        return D_ChaoBiaoRQ;
    }

    public void setD_ChaoBiaoRQ(long D_ChaoBiaoRQ) {
        this.D_ChaoBiaoRQ = D_ChaoBiaoRQ;
    }

    public int getI_ShangCiCM() {
        return I_ShangCiCM;
    }

    public void setI_ShangCiCM(int I_ShangCiCM) {
        this.I_ShangCiCM = I_ShangCiCM;
    }

    public int getI_BENCICM() {
        return I_BENCICM;
    }

    public void setI_BENCICM(int I_BENCICM) {
        this.I_BENCICM = I_BENCICM;
    }

    public int getI_CHAOJIANSL() {
        return I_CHAOJIANSL;
    }

    public void setI_CHAOJIANSL(int I_CHAOJIANSL) {
        this.I_CHAOJIANSL = I_CHAOJIANSL;
    }

    public String getS_CHAOBIAOZT() {
        return S_CHAOBIAOZT;
    }

    public void setS_CHAOBIAOZT(String S_CHAOBIAOZT) {
        this.S_CHAOBIAOZT = S_CHAOBIAOZT;
    }

    public String getS_ChaoBiaoY() {
        return S_ChaoBiaoY;
    }

    public void setS_ChaoBiaoY(String S_ChaoBiaoY) {
        this.S_ChaoBiaoY = S_ChaoBiaoY;
    }

    public String getS_CHAOBIAOBZ() {
        return S_CHAOBIAOBZ;
    }

    public void setS_CHAOBIAOBZ(String S_CHAOBIAOBZ) {
        this.S_CHAOBIAOBZ = S_CHAOBIAOBZ;
    }

    public int getI_CHAOBIAOZTBM() {
        return I_CHAOBIAOZTBM;
    }

    public void setI_CHAOBIAOZTBM(int I_CHAOBIAOZTBM) {
        this.I_CHAOBIAOZTBM = I_CHAOBIAOZTBM;
    }

    public int getI_LIANGGAOLDYYBM() {
        return I_LIANGGAOLDYYBM;
    }

    public void setI_LIANGGAOLDYYBM(int I_LIANGGAOLDYYBM) {
        this.I_LIANGGAOLDYYBM = I_LIANGGAOLDYYBM;
    }

}
