package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SX_GONGGAOXX.
 */
public class GongGaoXX {
    private int I_GongGaoBH;
    private String S_GongGaoBT;
    private String S_GongGaoNR;
    private String S_FaBuR;
    private long D_FaBuSJ;
    private String S_JieShouR;
    private String S_BeiZhu;
    private int I_SiFouYD;

    public GongGaoXX() {
    }

    public GongGaoXX(int I_GongGaoBH,
                     String S_GongGaoBT,
                     String S_GongGaoNR,
                     String S_FaBuR,
                     long D_FaBuSJ,
                     String S_JieShouR,
                     String S_BeiZhu,
                     int I_SiFouYD) {
        this.I_GongGaoBH = I_GongGaoBH;
        this.S_GongGaoBT = S_GongGaoBT;
        this.S_GongGaoNR = S_GongGaoNR;
        this.S_FaBuR = S_FaBuR;
        this.D_FaBuSJ = D_FaBuSJ;
        this.S_JieShouR = S_JieShouR;
        this.S_BeiZhu = S_BeiZhu;
        this.I_SiFouYD = I_SiFouYD;
    }

    public int getI_GongGaoBH() {
        return I_GongGaoBH;
    }

    public void setI_GongGaoBH(int I_GongGaoBH) {
        this.I_GongGaoBH = I_GongGaoBH;
    }

    public String getS_GongGaoBT() {
        return S_GongGaoBT;
    }

    public void setS_GongGaoBT(String S_GongGaoBT) {
        this.S_GongGaoBT = S_GongGaoBT;
    }

    public String getS_GongGaoNR() {
        return S_GongGaoNR;
    }

    public void setS_GongGaoNR(String S_GongGaoNR) {
        this.S_GongGaoNR = S_GongGaoNR;
    }

    public String getS_FaBuR() {
        return S_FaBuR;
    }

    public void setS_FaBuR(String S_FaBuR) {
        this.S_FaBuR = S_FaBuR;
    }

    public long getD_FaBuSJ() {
        return D_FaBuSJ;
    }

    public void setD_FaBuSJ(long D_FaBuSJ) {
        this.D_FaBuSJ = D_FaBuSJ;
    }

    public String getS_JieShouR() {
        return S_JieShouR;
    }

    public void setS_JieShouR(String S_JieShouR) {
        this.S_JieShouR = S_JieShouR;
    }

    public String getS_BeiZhu() {
        return S_BeiZhu;
    }

    public void setS_BeiZhu(String S_BeiZhu) {
        this.S_BeiZhu = S_BeiZhu;
    }

    public int getI_SiFouYD() {
        return I_SiFouYD;
    }

    public void setI_SiFouYD(int I_SiFouYD) {
        this.I_SiFouYD = I_SiFouYD;
    }

}
