package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BW_HuanBiaoJL.
 */
public class HuanBiaoJL {

    private String S_CID;
    private String S_BiaoWeiXX;
    private String S_DengJiR;
    private long D_DengJiRQ;
    private String S_HuanBiaoLX;
    private String S_HuanBiaoYY;
    private String S_JiubiaoBH;
    private String S_JiuBiaoGYH;
    private String S_JiuBiaoCJ;
    private String S_XinBiaoBH;
    private String S_XinBiaoGYH;
    private String S_XinBiaoCJ;
    private String S_JiuBiaoXH;
    private String S_XinBiaoXH;
    private String S_JiuBiaoKJ;
    private String S_XinBiaoKJ;
    private int I_XinBiaoLC;
    private int I_ShangCiCM;
    private int I_JiuBiaoCM;
    private int I_XinBiaoDM;
    private long D_ShiGongRQ;
    private String S_HuiTianR;
    private long D_HuanBiaoHTRQ;
    private String S_HuanBiaoZT;
    private String S_BeiZhu;

    public HuanBiaoJL() {
    }

    public HuanBiaoJL(String S_CID,
                      String S_BiaoWeiXX,
                      String S_DengJiR,
                      long D_DengJiRQ,
                      String S_HuanBiaoLX,
                      String S_HuanBiaoYY,
                      String S_JiubiaoBH,
                      String S_JiuBiaoGYH,
                      String S_JiuBiaoCJ,
                      String S_XinBiaoBH,
                      String S_XinBiaoGYH,
                      String S_XinBiaoCJ,
                      String S_JiuBiaoXH,
                      String S_XinBiaoXH,
                      String S_JiuBiaoKJ,
                      String S_XinBiaoKJ,
                      int I_XinBiaoLC,
                      int I_ShangCiCM,
                      int I_JiuBiaoCM,
                      int I_XinBiaoDM,
                      long D_ShiGongRQ,
                      String S_HuiTianR,
                      long D_HuanBiaoHTRQ,
                      String S_HuanBiaoZT,
                      String S_BeiZhu) {
        this.S_CID = S_CID;
        this.S_BiaoWeiXX = S_BiaoWeiXX;
        this.S_DengJiR = S_DengJiR;
        this.D_DengJiRQ = D_DengJiRQ;
        this.S_HuanBiaoLX = S_HuanBiaoLX;
        this.S_HuanBiaoYY = S_HuanBiaoYY;
        this.S_JiubiaoBH = S_JiubiaoBH;
        this.S_JiuBiaoGYH = S_JiuBiaoGYH;
        this.S_JiuBiaoCJ = S_JiuBiaoCJ;
        this.S_XinBiaoBH = S_XinBiaoBH;
        this.S_XinBiaoGYH = S_XinBiaoGYH;
        this.S_XinBiaoCJ = S_XinBiaoCJ;
        this.S_JiuBiaoXH = S_JiuBiaoXH;
        this.S_XinBiaoXH = S_XinBiaoXH;
        this.S_JiuBiaoKJ = S_JiuBiaoKJ;
        this.S_XinBiaoKJ = S_XinBiaoKJ;
        this.I_XinBiaoLC = I_XinBiaoLC;
        this.I_ShangCiCM = I_ShangCiCM;
        this.I_JiuBiaoCM = I_JiuBiaoCM;
        this.I_XinBiaoDM = I_XinBiaoDM;
        this.D_ShiGongRQ = D_ShiGongRQ;
        this.S_HuiTianR = S_HuiTianR;
        this.D_HuanBiaoHTRQ = D_HuanBiaoHTRQ;
        this.S_HuanBiaoZT = S_HuanBiaoZT;
        this.S_BeiZhu = S_BeiZhu;
    }

    public String getS_CID() {
        return S_CID;
    }

    public void setS_CID(String S_CID) {
        this.S_CID = S_CID;
    }

    public String getS_BiaoWeiXX() {
        return S_BiaoWeiXX;
    }

    public void setS_BiaoWeiXX(String S_BiaoWeiXX) {
        this.S_BiaoWeiXX = S_BiaoWeiXX;
    }

    public String getS_DengJiR() {
        return S_DengJiR;
    }

    public void setS_DengJiR(String S_DengJiR) {
        this.S_DengJiR = S_DengJiR;
    }

    public long getD_DengJiRQ() {
        return D_DengJiRQ;
    }

    public void setD_DengJiRQ(long D_DengJiRQ) {
        this.D_DengJiRQ = D_DengJiRQ;
    }

    public String getS_HuanBiaoLX() {
        return S_HuanBiaoLX;
    }

    public void setS_HuanBiaoLX(String S_HuanBiaoLX) {
        this.S_HuanBiaoLX = S_HuanBiaoLX;
    }

    public String getS_HuanBiaoYY() {
        return S_HuanBiaoYY;
    }

    public void setS_HuanBiaoYY(String S_HuanBiaoYY) {
        this.S_HuanBiaoYY = S_HuanBiaoYY;
    }

    public String getS_JiubiaoBH() {
        return S_JiubiaoBH;
    }

    public void setS_JiubiaoBH(String S_JiubiaoBH) {
        this.S_JiubiaoBH = S_JiubiaoBH;
    }

    public String getS_JiuBiaoGYH() {
        return S_JiuBiaoGYH;
    }

    public void setS_JiuBiaoGYH(String S_JiuBiaoGYH) {
        this.S_JiuBiaoGYH = S_JiuBiaoGYH;
    }

    public String getS_JiuBiaoCJ() {
        return S_JiuBiaoCJ;
    }

    public void setS_JiuBiaoCJ(String S_JiuBiaoCJ) {
        this.S_JiuBiaoCJ = S_JiuBiaoCJ;
    }

    public String getS_XinBiaoBH() {
        return S_XinBiaoBH;
    }

    public void setS_XinBiaoBH(String S_XinBiaoBH) {
        this.S_XinBiaoBH = S_XinBiaoBH;
    }

    public String getS_XinBiaoGYH() {
        return S_XinBiaoGYH;
    }

    public void setS_XinBiaoGYH(String S_XinBiaoGYH) {
        this.S_XinBiaoGYH = S_XinBiaoGYH;
    }

    public String getS_XinBiaoCJ() {
        return S_XinBiaoCJ;
    }

    public void setS_XinBiaoCJ(String S_XinBiaoCJ) {
        this.S_XinBiaoCJ = S_XinBiaoCJ;
    }

    public String getS_JiuBiaoXH() {
        return S_JiuBiaoXH;
    }

    public void setS_JiuBiaoXH(String S_JiuBiaoXH) {
        this.S_JiuBiaoXH = S_JiuBiaoXH;
    }

    public String getS_XinBiaoXH() {
        return S_XinBiaoXH;
    }

    public void setS_XinBiaoXH(String S_XinBiaoXH) {
        this.S_XinBiaoXH = S_XinBiaoXH;
    }

    public String getS_JiuBiaoKJ() {
        return S_JiuBiaoKJ;
    }

    public void setS_JiuBiaoKJ(String S_JiuBiaoKJ) {
        this.S_JiuBiaoKJ = S_JiuBiaoKJ;
    }

    public String getS_XinBiaoKJ() {
        return S_XinBiaoKJ;
    }

    public void setS_XinBiaoKJ(String S_XinBiaoKJ) {
        this.S_XinBiaoKJ = S_XinBiaoKJ;
    }

    public int getI_XinBiaoLC() {
        return I_XinBiaoLC;
    }

    public void setI_XinBiaoLC(int I_XinBiaoLC) {
        this.I_XinBiaoLC = I_XinBiaoLC;
    }

    public int getI_ShangCiCM() {
        return I_ShangCiCM;
    }

    public void setI_ShangCiCM(int I_ShangCiCM) {
        this.I_ShangCiCM = I_ShangCiCM;
    }

    public int getI_JiuBiaoCM() {
        return I_JiuBiaoCM;
    }

    public void setI_JiuBiaoCM(int I_JiuBiaoCM) {
        this.I_JiuBiaoCM = I_JiuBiaoCM;
    }

    public int getI_XinBiaoDM() {
        return I_XinBiaoDM;
    }

    public void setI_XinBiaoDM(int I_XinBiaoDM) {
        this.I_XinBiaoDM = I_XinBiaoDM;
    }

    public long getD_ShiGongRQ() {
        return D_ShiGongRQ;
    }

    public void setD_ShiGongRQ(long D_ShiGongRQ) {
        this.D_ShiGongRQ = D_ShiGongRQ;
    }

    public String getS_HuiTianR() {
        return S_HuiTianR;
    }

    public void setS_HuiTianR(String S_HuiTianR) {
        this.S_HuiTianR = S_HuiTianR;
    }

    public long getD_HuanBiaoHTRQ() {
        return D_HuanBiaoHTRQ;
    }

    public void setD_HuanBiaoHTRQ(long D_HuanBiaoHTRQ) {
        this.D_HuanBiaoHTRQ = D_HuanBiaoHTRQ;
    }

    public String getS_HuanBiaoZT() {
        return S_HuanBiaoZT;
    }

    public void setS_HuanBiaoZT(String S_HuanBiaoZT) {
        this.S_HuanBiaoZT = S_HuanBiaoZT;
    }

    public String getS_BeiZhu() {
        return S_BeiZhu;
    }

    public void setS_BeiZhu(String S_BeiZhu) {
        this.S_BeiZhu = S_BeiZhu;
    }

}
