package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JG_JianHaoMX.
 */
public class JianHaoMX {

    private int ID;
    private int I_TIAOJIAH;
    /** Not-null value. */
    private String S_JIANHAO;
    private int I_FEIYONGDLID;
    private int I_FEIYONGID;
    private int I_QISHIY;
    private int I_JIESHUY;
    private int I_KAISHISL;
    private int I_JIESHUSL;
    private int I_JIETIJB;
    private double N_ZHEKOUL;
    private int I_ZHEKOULX;
    private double N_JIAGE;
    private String _feiYongMC;
    private double _xiShu;

    private int _jieTiS;
    private String _daLei;
    private String _zhongLei;

    public JianHaoMX() {
    }

    public JianHaoMX(int ID, int I_TIAOJIAH, String S_JIANHAO,
                     int I_FEIYONGDLID, int I_FEIYONGID,
                     int I_QISHIY, int I_JIESHUY, int I_KAISHISL,
                     int I_JIESHUSL, int I_JIETIJB, double N_ZHEKOUL,
                     int I_ZHEKOULX, double N_JIAGE) {
        this.ID = ID;
        this.I_TIAOJIAH = I_TIAOJIAH;
        this.S_JIANHAO = S_JIANHAO;
        this.I_FEIYONGDLID = I_FEIYONGDLID;
        this.I_FEIYONGID = I_FEIYONGID;
        this.I_QISHIY = I_QISHIY;
        this.I_JIESHUY = I_JIESHUY;
        this.I_KAISHISL = I_KAISHISL;
        this.I_JIESHUSL = I_JIESHUSL;
        this.I_JIETIJB = I_JIETIJB;
        this.N_ZHEKOUL = N_ZHEKOUL;
        this.I_ZHEKOULX = I_ZHEKOULX;
        this.N_JIAGE = N_JIAGE;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public int getI_TIAOJIAH() {
        return I_TIAOJIAH;
    }

    public void setI_TIAOJIAH(int I_TIAOJIAH) {
        this.I_TIAOJIAH = I_TIAOJIAH;
    }

    /** Not-null value. */
    public String getS_JIANHAO() {
        return S_JIANHAO;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_JIANHAO(String S_JIANHAO) {
        this.S_JIANHAO = S_JIANHAO;
    }

    public int getI_FEIYONGDLID() {
        return I_FEIYONGDLID;
    }

    public void setI_FEIYONGDLID(int I_FEIYONGDLID) {
        this.I_FEIYONGDLID = I_FEIYONGDLID;
    }

    public int getI_FEIYONGID() {
        return I_FEIYONGID;
    }

    public void setI_FEIYONGID(int I_FEIYONGID) {
        this.I_FEIYONGID = I_FEIYONGID;
    }

    public int getI_QISHIY() {
        return I_QISHIY;
    }

    public void setI_QISHIY(int I_QISHIY) {
        this.I_QISHIY = I_QISHIY;
    }

    public int getI_JIESHUY() {
        return I_JIESHUY;
    }

    public void setI_JIESHUY(int I_JIESHUY) {
        this.I_JIESHUY = I_JIESHUY;
    }

    public int getI_KAISHISL() {
        return I_KAISHISL;
    }

    public void setI_KAISHISL(int I_KAISHISL) {
        this.I_KAISHISL = I_KAISHISL;
    }

    public int getI_JIESHUSL() {
        return I_JIESHUSL;
    }

    public void setI_JIESHUSL(int I_JIESHUSL) {
        this.I_JIESHUSL = I_JIESHUSL;
    }

    public int getI_JIETIJB() {
        return I_JIETIJB;
    }

    public void setI_JIETIJB(int I_JIETIJB) {
        this.I_JIETIJB = I_JIETIJB;
    }

    public double getN_ZHEKOUL() {
        return N_ZHEKOUL;
    }

    public void setN_ZHEKOUL(double N_ZHEKOUL) {
        this.N_ZHEKOUL = N_ZHEKOUL;
    }

    public int getI_ZHEKOULX() {
        return I_ZHEKOULX;
    }

    public void setI_ZHEKOULX(int I_ZHEKOULX) {
        this.I_ZHEKOULX = I_ZHEKOULX;
    }

    public double getN_JIAGE() {
        return N_JIAGE;
    }

    public void setN_JIAGE(double N_JIAGE) {
        this.N_JIAGE = N_JIAGE;
    }

    public String get_feiYongMC() {
        return _feiYongMC;
    }

    public void set_feiYongMC(String _feiYongMC) {
        this._feiYongMC = _feiYongMC;
    }
    /**
     * 获取系数
     * @return
     */
    public double getxiShu() {
        return _xiShu;
    }

    /**
     * 设置系数
     * @param _xiShu
     */
    public void setxiShu(double _xiShu) {
        this._xiShu = _xiShu;
    }
    /**
     * 获取阶梯数
     * @return
     */
    public int getjieTiS() {
        return _jieTiS;
    }

    /**
     * 设置阶梯数
     * @param _jieTiS
     */
    public void setjieTiS(int _jieTiS) {
        this._jieTiS = _jieTiS;
    }

    /**
     * 获取大类
     * @return
     */
    public String getdaLei() {
        return _daLei;
    }

    public void setdaLei(String _daLei) {
        this._daLei = _daLei;
    }
    /**
     * 获取简号中类名称
     * @return
     */
    public String getzhongLei() {
        return _zhongLei;
    }

    public void setzhongLei(String _zhongLei) {
        this._zhongLei = _zhongLei;
    }
}
