package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JG_JianHao.
 */
public class JianHao {

    private int ID;
    private int I_TIAOJIAH;
    private String S_DALEI;
    private String S_ZHONGLEI;
    private String S_XIAOLEI;
    /** Not-null value. */
    private String S_JIANHAO;
    private int I_JIETIS;
    private String S_BEIZHU;

    public JianHao() {
    }

    public JianHao(int ID, int I_TIAOJIAH, String S_DALEI, String S_ZHONGLEI,
                   String S_XIAOLEI, String S_JIANHAO, int I_JIETIS, String S_BEIZHU) {
        this.ID = ID;
        this.I_TIAOJIAH = I_TIAOJIAH;
        this.S_DALEI = S_DALEI;
        this.S_ZHONGLEI = S_ZHONGLEI;
        this.S_XIAOLEI = S_XIAOLEI;
        this.S_JIANHAO = S_JIANHAO;
        this.I_JIETIS = I_JIETIS;
        this.S_BEIZHU = S_BEIZHU;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public int getI_TIAOJIAH() {
        return I_TIAOJIAH;
    }

    public void setI_TIAOJIAH(int I_TIAOJIAH) {
        this.I_TIAOJIAH = I_TIAOJIAH;
    }

    public String getS_DALEI() {
        return S_DALEI;
    }

    public void setS_DALEI(String S_DALEI) {
        this.S_DALEI = S_DALEI;
    }

    public String getS_ZHONGLEI() {
        return S_ZHONGLEI;
    }

    public void setS_ZHONGLEI(String S_ZHONGLEI) {
        this.S_ZHONGLEI = S_ZHONGLEI;
    }

    public String getS_XIAOLEI() {
        return S_XIAOLEI;
    }

    public void setS_XIAOLEI(String S_XIAOLEI) {
        this.S_XIAOLEI = S_XIAOLEI;
    }

    /** Not-null value. */
    public String getS_JIANHAO() {
        return S_JIANHAO;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_JIANHAO(String S_JIANHAO) {
        this.S_JIANHAO = S_JIANHAO;
    }

    public int getI_JIETIS() {
        return I_JIETIS;
    }

    public void setI_JIETIS(int I_JIETIS) {
        this.I_JIETIS = I_JIETIS;
    }

    public String getS_BEIZHU() {
        return S_BEIZHU;
    }

    public void setS_BEIZHU(String S_BEIZHU) {
        this.S_BEIZHU = S_BEIZHU;
    }

}
