package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SF_JiaoFeiXX.
 */
public class JiaoFeiXX {

    /** Not-null value. */
    private String S_CID;
    private int I_ZhangWuNY;
    private int I_FEEID;
    private long D_ChaoBiaoRQ;
    private long D_KAIZHANGRQ;
    private long D_SHOUFEIRQ;
    private double N_JE;
    private double N_SHISHOUWYJ;
    private double N_SHISHOUZJE;
    private String S_SHOUFEITJ;

    public JiaoFeiXX() {
    }

    public JiaoFeiXX(String S_CID,
                     int I_ZhangWuNY,
                     int I_FEEID,
                     long D_ChaoBiaoRQ,
                     long D_KAIZHANGRQ,
                     long D_SHOUFEIRQ,
                     double N_JE,
                     double N_SHISHOUWYJ,
                     double N_SHISHOUZJE,
                     String S_SHOUFEITJ) {
        this.S_CID = S_CID;
        this.I_ZhangWuNY = I_ZhangWuNY;
        this.I_FEEID = I_FEEID;
        this.D_ChaoBiaoRQ = D_ChaoBiaoRQ;
        this.D_KAIZHANGRQ = D_KAIZHANGRQ;
        this.D_SHOUFEIRQ = D_SHOUFEIRQ;
        this.N_JE = N_JE;
        this.N_SHISHOUWYJ = N_SHISHOUWYJ;
        this.N_SHISHOUZJE = N_SHISHOUZJE;
        this.S_SHOUFEITJ = S_SHOUFEITJ;
    }

    /** Not-null value. */
    public String getS_CID() {
        return S_CID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_CID(String S_CID) {
        this.S_CID = S_CID;
    }

    public int getI_ZhangWuNY() {
        return I_ZhangWuNY;
    }

    public void setI_ZhangWuNY(int I_ZhangWuNY) {
        this.I_ZhangWuNY = I_ZhangWuNY;
    }

    public int getI_FEEID() {
        return I_FEEID;
    }

    public void setI_FEEID(int I_FEEID) {
        this.I_FEEID = I_FEEID;
    }

    public long getD_ChaoBiaoRQ() {
        return D_ChaoBiaoRQ;
    }

    public void setD_ChaoBiaoRQ(long D_ChaoBiaoRQ) {
        this.D_ChaoBiaoRQ = D_ChaoBiaoRQ;
    }

    public long getD_KAIZHANGRQ() {
        return D_KAIZHANGRQ;
    }

    public void setD_KAIZHANGRQ(long D_KAIZHANGRQ) {
        this.D_KAIZHANGRQ = D_KAIZHANGRQ;
    }

    public long getD_SHOUFEIRQ() {
        return D_SHOUFEIRQ;
    }

    public void setD_SHOUFEIRQ(long D_SHOUFEIRQ) {
        this.D_SHOUFEIRQ = D_SHOUFEIRQ;
    }

    public double getN_JE() {
        return N_JE;
    }

    public void setN_JE(double N_JE) {
        this.N_JE = N_JE;
    }

    public double getN_SHISHOUWYJ() {
        return N_SHISHOUWYJ;
    }

    public void setN_SHISHOUWYJ(double N_SHISHOUWYJ) {
        this.N_SHISHOUWYJ = N_SHISHOUWYJ;
    }

    public double getN_SHISHOUZJE() {
        return N_SHISHOUZJE;
    }

    public void setN_SHISHOUZJE(double N_SHISHOUZJE) {
        this.N_SHISHOUZJE = N_SHISHOUZJE;
    }

    public String getS_SHOUFEITJ() {
        return S_SHOUFEITJ;
    }

    public void setS_SHOUFEITJ(String S_SHOUFEITJ) {
        this.S_SHOUFEITJ = S_SHOUFEITJ;
    }

}
