package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PDA_RENWUXX.
 */
public class RenwuXX {

    private Integer ID;
    private Integer I_RENWUBH;
    private Integer I_TYPE;
    private Integer D_CREATESJ;
    private Integer D_PAIFASJ;
    private Integer D_HUITIANSJ;
    private Integer I_STAIE;
    private String S_ACCOUNT;
    private Integer I_SUBTYPE;

    public RenwuXX() {
    }

    public RenwuXX(Integer ID, Integer I_RENWUBH, Integer I_TYPE, Integer D_CREATESJ, Integer D_PAIFASJ, Integer D_HUITIANSJ, Integer I_STAIE, String S_ACCOUNT, Integer I_SUBTYPE) {
        this.ID = ID;
        this.I_RENWUBH = I_RENWUBH;
        this.I_TYPE = I_TYPE;
        this.D_CREATESJ = D_CREATESJ;
        this.D_PAIFASJ = D_PAIFASJ;
        this.D_HUITIANSJ = D_HUITIANSJ;
        this.I_STAIE = I_STAIE;
        this.S_ACCOUNT = S_ACCOUNT;
        this.I_SUBTYPE = I_SUBTYPE;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public Integer getI_RENWUBH() {
        return I_RENWUBH;
    }

    public void setI_RENWUBH(Integer I_RENWUBH) {
        this.I_RENWUBH = I_RENWUBH;
    }

    public Integer getI_TYPE() {
        return I_TYPE;
    }

    public void setI_TYPE(Integer I_TYPE) {
        this.I_TYPE = I_TYPE;
    }

    public Integer getD_CREATESJ() {
        return D_CREATESJ;
    }

    public void setD_CREATESJ(Integer D_CREATESJ) {
        this.D_CREATESJ = D_CREATESJ;
    }

    public Integer getD_PAIFASJ() {
        return D_PAIFASJ;
    }

    public void setD_PAIFASJ(Integer D_PAIFASJ) {
        this.D_PAIFASJ = D_PAIFASJ;
    }

    public Integer getD_HUITIANSJ() {
        return D_HUITIANSJ;
    }

    public void setD_HUITIANSJ(Integer D_HUITIANSJ) {
        this.D_HUITIANSJ = D_HUITIANSJ;
    }

    public Integer getI_STAIE() {
        return I_STAIE;
    }

    public void setI_STAIE(Integer I_STAIE) {
        this.I_STAIE = I_STAIE;
    }

    public String getS_ACCOUNT() {
        return S_ACCOUNT;
    }

    public void setS_ACCOUNT(String S_ACCOUNT) {
        this.S_ACCOUNT = S_ACCOUNT;
    }

    public Integer getI_SUBTYPE() {
        return I_SUBTYPE;
    }

    public void setI_SUBTYPE(Integer I_SUBTYPE) {
        this.I_SUBTYPE = I_SUBTYPE;
    }

}
