package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table KG_ShuiLiangFTXX.
 */
public class ShuiLiangFTXX {

    /** Not-null value. */
    private String S_CID;
    /** Not-null value. */
    private String S_JianHao;
    private int I_FenTanFS;
    private double I_FenTanL;
    private int I_PaiXu;

    public ShuiLiangFTXX() {
    }

    public ShuiLiangFTXX(String S_CID,
                         String S_JianHao,
                         int I_FenTanFS,
                         double I_FenTanL,
                         int I_PaiXu) {
        this.S_CID = S_CID;
        this.S_JianHao = S_JianHao;
        this.I_FenTanFS = I_FenTanFS;
        this.I_FenTanL = I_FenTanL;
        this.I_PaiXu = I_PaiXu;
    }

    /** Not-null value. */
    public String getS_CID() {
        return S_CID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_CID(String S_CID) {
        this.S_CID = S_CID;
    }

    /** Not-null value. */
    public String getS_JianHao() {
        return S_JianHao;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_JianHao(String S_JianHao) {
        this.S_JianHao = S_JianHao;
    }

    public int getI_FenTanFS() {
        return I_FenTanFS;
    }

    public void setI_FenTanFS(int I_FenTanFS) {
        this.I_FenTanFS = I_FenTanFS;
    }

    public double getI_FenTanL() {
        return I_FenTanL;
    }

    public void setI_FenTanL(double I_FenTanL) {
        this.I_FenTanL = I_FenTanL;
    }

    public int getI_PaiXu() {
        return I_PaiXu;
    }

    public void setI_PaiXu(int I_PaiXu) {
        this.I_PaiXu = I_PaiXu;
    }

}
