package com.sh3h.dataprovider.greendaoEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.sh3h.dataprovider.entity.ResultInfo;

/**
 * Entity mapped to table PDA_WaiFuGDMain.
 */
public class WaiFuGDMain {

    private int I_RENWUBH;
    private Integer I_TYPE;
    /** Not-null value. */
    private String S_CID;
    /** Not-null value. */
    private String S_CH;
    private String S_HM;
    private String S_DZ;
    private String S_DIANHUAHM;
    private String S_JH_OLD;
    private String S_JH_NEW;
    private Integer D_TIJIAORQ;
    private String S_SHENQINGR;
    private String S_SHENQINGYY;
    private Integer I_RENKOUS;
    private Integer I_YOUHUISL;
    private Integer I_DUNWEIS;
    private Integer B_QUANER;
    private Integer I_SHANGCHUANBZ;
    private Integer I_LAIYUANBH;
    private String S_CAOZUOR;
    private Integer I_WANCHENGBZ;
    private Integer I_HESHIRKS;
    private Integer I_HESHIDWS;
    private Integer D_SHIGONGRQ;
    private String S_HECHAQK;
    private String S_SHENHEYJ;
    private Integer I_SHENPIJG;
    private String S_FUHEYJYY;
    private String S_BEIZHU;
    private String S_TIAOXINGM;
    private String S_KEHUQM;
    private String S_ZHAOPIANMC;
    private String S_X1;
    private String S_Y1;
    private ResultInfo resultInfo;

    public WaiFuGDMain() {
    }

    public WaiFuGDMain(int I_RENWUBH, Integer I_TYPE, String S_CID, String S_CH, String S_HM, String S_DZ, String S_DIANHUAHM, String S_JH_OLD, String S_JH_NEW, Integer D_TIJIAORQ, String S_SHENQINGR, String S_SHENQINGYY, Integer I_RENKOUS, Integer I_YOUHUISL, Integer I_DUNWEIS, Integer B_QUANER, Integer I_SHANGCHUANBZ, Integer I_LAIYUANBH, String S_CAOZUOR, Integer I_WANCHENGBZ, Integer I_HESHIRKS, Integer I_HESHIDWS, Integer D_SHIGONGRQ, String S_HECHAQK, String S_SHENHEYJ, Integer I_SHENPIJG, String S_FUHEYJYY, String S_BEIZHU, String S_TIAOXINGM, String S_KEHUQM, String S_ZHAOPIANMC, String S_X1, String S_Y1) {
        this.I_RENWUBH = I_RENWUBH;
        this.I_TYPE = I_TYPE;
        this.S_CID = S_CID;
        this.S_CH = S_CH;
        this.S_HM = S_HM;
        this.S_DZ = S_DZ;
        this.S_DIANHUAHM = S_DIANHUAHM;
        this.S_JH_OLD = S_JH_OLD;
        this.S_JH_NEW = S_JH_NEW;
        this.D_TIJIAORQ = D_TIJIAORQ;
        this.S_SHENQINGR = S_SHENQINGR;
        this.S_SHENQINGYY = S_SHENQINGYY;
        this.I_RENKOUS = I_RENKOUS;
        this.I_YOUHUISL = I_YOUHUISL;
        this.I_DUNWEIS = I_DUNWEIS;
        this.B_QUANER = B_QUANER;
        this.I_SHANGCHUANBZ = I_SHANGCHUANBZ;
        this.I_LAIYUANBH = I_LAIYUANBH;
        this.S_CAOZUOR = S_CAOZUOR;
        this.I_WANCHENGBZ = I_WANCHENGBZ;
        this.I_HESHIRKS = I_HESHIRKS;
        this.I_HESHIDWS = I_HESHIDWS;
        this.D_SHIGONGRQ = D_SHIGONGRQ;
        this.S_HECHAQK = S_HECHAQK;
        this.S_SHENHEYJ = S_SHENHEYJ;
        this.I_SHENPIJG = I_SHENPIJG;
        this.S_FUHEYJYY = S_FUHEYJYY;
        this.S_BEIZHU = S_BEIZHU;
        this.S_TIAOXINGM = S_TIAOXINGM;
        this.S_KEHUQM = S_KEHUQM;
        this.S_ZHAOPIANMC = S_ZHAOPIANMC;
        this.S_X1 = S_X1;
        this.S_Y1 = S_Y1;
    }

    public int getI_RENWUBH() {
        return I_RENWUBH;
    }

    public void setI_RENWUBH(int I_RENWUBH) {
        this.I_RENWUBH = I_RENWUBH;
    }

    public Integer getI_TYPE() {
        return I_TYPE;
    }

    public void setI_TYPE(Integer I_TYPE) {
        this.I_TYPE = I_TYPE;
    }

    /** Not-null value. */
    public String getS_CID() {
        return S_CID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_CID(String S_CID) {
        this.S_CID = S_CID;
    }

    /** Not-null value. */
    public String getS_CH() {
        return S_CH;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_CH(String S_CH) {
        this.S_CH = S_CH;
    }

    public String getS_HM() {
        return S_HM;
    }

    public void setS_HM(String S_HM) {
        this.S_HM = S_HM;
    }

    public String getS_DZ() {
        return S_DZ;
    }

    public void setS_DZ(String S_DZ) {
        this.S_DZ = S_DZ;
    }

    public String getS_DIANHUAHM() {
        return S_DIANHUAHM;
    }

    public void setS_DIANHUAHM(String S_DIANHUAHM) {
        this.S_DIANHUAHM = S_DIANHUAHM;
    }

    public String getS_JH_OLD() {
        return S_JH_OLD;
    }

    public void setS_JH_OLD(String S_JH_OLD) {
        this.S_JH_OLD = S_JH_OLD;
    }

    public String getS_JH_NEW() {
        return S_JH_NEW;
    }

    public void setS_JH_NEW(String S_JH_NEW) {
        this.S_JH_NEW = S_JH_NEW;
    }

    public Integer getD_TIJIAORQ() {
        return D_TIJIAORQ;
    }

    public void setD_TIJIAORQ(Integer D_TIJIAORQ) {
        this.D_TIJIAORQ = D_TIJIAORQ;
    }

    public String getS_SHENQINGR() {
        return S_SHENQINGR;
    }

    public void setS_SHENQINGR(String S_SHENQINGR) {
        this.S_SHENQINGR = S_SHENQINGR;
    }

    public String getS_SHENQINGYY() {
        return S_SHENQINGYY;
    }

    public void setS_SHENQINGYY(String S_SHENQINGYY) {
        this.S_SHENQINGYY = S_SHENQINGYY;
    }

    public Integer getI_RENKOUS() {
        return I_RENKOUS;
    }

    public void setI_RENKOUS(Integer I_RENKOUS) {
        this.I_RENKOUS = I_RENKOUS;
    }

    public Integer getI_YOUHUISL() {
        return I_YOUHUISL;
    }

    public void setI_YOUHUISL(Integer I_YOUHUISL) {
        this.I_YOUHUISL = I_YOUHUISL;
    }

    public Integer getI_DUNWEIS() {
        return I_DUNWEIS;
    }

    public void setI_DUNWEIS(Integer I_DUNWEIS) {
        this.I_DUNWEIS = I_DUNWEIS;
    }

    public Integer getB_QUANER() {
        return B_QUANER;
    }

    public void setB_QUANER(Integer B_QUANER) {
        this.B_QUANER = B_QUANER;
    }

    public Integer getI_SHANGCHUANBZ() {
        return I_SHANGCHUANBZ;
    }

    public void setI_SHANGCHUANBZ(Integer I_SHANGCHUANBZ) {
        this.I_SHANGCHUANBZ = I_SHANGCHUANBZ;
    }

    public Integer getI_LAIYUANBH() {
        return I_LAIYUANBH;
    }

    public void setI_LAIYUANBH(Integer I_LAIYUANBH) {
        this.I_LAIYUANBH = I_LAIYUANBH;
    }

    public String getS_CAOZUOR() {
        return S_CAOZUOR;
    }

    public void setS_CAOZUOR(String S_CAOZUOR) {
        this.S_CAOZUOR = S_CAOZUOR;
    }

    public Integer getI_WANCHENGBZ() {
        return I_WANCHENGBZ;
    }

    public void setI_WANCHENGBZ(Integer I_WANCHENGBZ) {
        this.I_WANCHENGBZ = I_WANCHENGBZ;
    }

    public Integer getI_HESHIRKS() {
        return I_HESHIRKS;
    }

    public void setI_HESHIRKS(Integer I_HESHIRKS) {
        this.I_HESHIRKS = I_HESHIRKS;
    }

    public Integer getI_HESHIDWS() {
        return I_HESHIDWS;
    }

    public void setI_HESHIDWS(Integer I_HESHIDWS) {
        this.I_HESHIDWS = I_HESHIDWS;
    }

    public Integer getD_SHIGONGRQ() {
        return D_SHIGONGRQ;
    }

    public void setD_SHIGONGRQ(Integer D_SHIGONGRQ) {
        this.D_SHIGONGRQ = D_SHIGONGRQ;
    }

    public String getS_HECHAQK() {
        return S_HECHAQK;
    }

    public void setS_HECHAQK(String S_HECHAQK) {
        this.S_HECHAQK = S_HECHAQK;
    }

    public String getS_SHENHEYJ() {
        return S_SHENHEYJ;
    }

    public void setS_SHENHEYJ(String S_SHENHEYJ) {
        this.S_SHENHEYJ = S_SHENHEYJ;
    }

    public Integer getI_SHENPIJG() {
        return I_SHENPIJG;
    }

    public void setI_SHENPIJG(Integer I_SHENPIJG) {
        this.I_SHENPIJG = I_SHENPIJG;
    }

    public String getS_FUHEYJYY() {
        return S_FUHEYJYY;
    }

    public void setS_FUHEYJYY(String S_FUHEYJYY) {
        this.S_FUHEYJYY = S_FUHEYJYY;
    }

    public String getS_BEIZHU() {
        return S_BEIZHU;
    }

    public void setS_BEIZHU(String S_BEIZHU) {
        this.S_BEIZHU = S_BEIZHU;
    }

    public String getS_TIAOXINGM() {
        return S_TIAOXINGM;
    }

    public void setS_TIAOXINGM(String S_TIAOXINGM) {
        this.S_TIAOXINGM = S_TIAOXINGM;
    }

    public String getS_KEHUQM() {
        return S_KEHUQM;
    }

    public void setS_KEHUQM(String S_KEHUQM) {
        this.S_KEHUQM = S_KEHUQM;
    }

    public String getS_ZHAOPIANMC() {
        return S_ZHAOPIANMC;
    }

    public void setS_ZHAOPIANMC(String S_ZHAOPIANMC) {
        this.S_ZHAOPIANMC = S_ZHAOPIANMC;
    }

    public String getS_X1() {
        return S_X1;
    }

    public void setS_X1(String S_X1) {
        this.S_X1 = S_X1;
    }

    public String getS_Y1() {
        return S_Y1;
    }

    public void setS_Y1(String S_Y1) {
        this.S_Y1 = S_Y1;
    }

    public ResultInfo getResultInfo() {
        return resultInfo;
    }

    public void setResultInfo(ResultInfo resultInfo) {
        this.resultInfo = resultInfo;
    }
}
