package com.sh3h.meterreading.service;


public enum SyncType {
    UPLOADING_DOWNLOADING_ALL, // all volumes of tasks
    UPLOADING_DOWNLOADING_ALL_SAMPLING_TASKS,
    UPLOADING_DOWNLOADING_ALL_RUSH_PAY_TASKS, // all rushPay of tasks
    DOWNLOADING_VOLUME, // all volumes data of one task
    UPLOADING_VOLUME, // records && medias in one volume
    UPLOADING_RECORD_MEDIAS, // one record && medias
    UPLOADING_OUT_RECORD_MEDIAS, // one out record && medias
    DOWNLOADING_ALL_DETAIL_INFO,
    DOWNLOADING_DETAIL_INFO,
    QUERYING_QIANFEI,
    UPLOADING_CARD_COORDINATE,
    UPLOADING_SAMPLING,
    UPLOADING_SAMPLING_MEDIAS,
    DOWNLOADING_SAMPLING,
//    UPLOADING_DOWNLOADING_ALL_DATA,
    UPDATING_VOLUME_CARD,
    SYNC_WAIFUCBSJS,
    UPLOADING_WAIFUCBSJS_MEDIAS,
    UPLOADING_ALL_MEDIA_REPEATEDLY,
    UPLOADING_RUSH_PAY_MEDIAS,
    UPLOADING_DOWNLOADING_DELAY_ALL,
    UPLOADING_DELAY, // records && medias in one volume
    DOWNLOAD_DELAY
}
